-- Platform Cost & Attribution 1.1.0 — Cortex Agent
--
-- One agent per data product. It can reach this product's semantic view,
-- its search service, and its published views — nothing else.
--
-- Surfaced in Snowflake Intelligence to any role holding USAGE on the
-- agent; grants are in the grants script.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).
USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE AGENT OBSERVABILITY.AGENT.FINOPS_CHARGEBACK_AGENT
  COMMENT = 'Conversational interface to Platform Cost & Attribution 1.1.0. Scoped to the product''s semantic view; quotes tool results only.'
  PROFILE = '{"display_name": "Platform Cost & Attribution Copilot"}'
  FROM SPECIFICATION $$
orchestration:
  budget:
    seconds: 120
    tokens: 32000
instructions:
  response: 'You answer questions about Platform Cost & Attribution, an observability data product owned
    by finops-platform. Scope: V_FINOPS_CHARGEBACK_QUERY_EXECUTION, V_FINOPS_CHARGEBACK_COST_DAILY, V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY.
    Every number you state must come from a tool result. Never compute, estimate, extrapolate, or round
    a figure yourself; if a tool did not return it, say you cannot ground the claim and offer the question
    you could answer instead. State the time range and the as-of point of every figure. This product''s
    freshness guarantee is 480 minutes, which is the documented latency of its slowest source: never imply
    a figure is fresher than that, and say so when a user asks about the last hour. A null is not a zero.
    If a measure is null, report it as unknown for that slice and explain why, rather than reporting no
    activity. Cite the relation and the governed metric behind each figure so the user can check it. Answer
    only from this product; if a question needs data outside V_FINOPS_CHARGEBACK_QUERY_EXECUTION, V_FINOPS_CHARGEBACK_COST_DAILY,
    V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY, say which product would have it.'
  orchestration: Decompose the question first. If it asks how much, how many, a trend, or a comparison,
    use the analyst tool over the semantic view. This product has no free-text search; do not attempt
    one. Use the SQL tool only to follow up on a result the analyst tool already returned, and only against
    this product's published views. Never invent a dimension value. If a filter value does not appear
    in the data, say so rather than returning an empty result as if it were zero. If a question is ambiguous
    between two slices, ask which one before answering.
  sample_questions:
  - question: allocated credits by team
  - question: credits by team this month
  - question: unattributed credits by warehouse
  - question: how much of the allocation is estimated
  - question: metered credits by service type
  - question: billed credits this month
tools:
- tool_spec:
    type: cortex_analyst_text_to_sql
    name: finops_chargeback_analyst
    description: 'Answer aggregate, trend, and comparison questions about Platform Cost & Attribution
      from its governed semantic view. Covers 7 metrics: chargeback.allocated_credits, chargeback.metered_credits,
      chargeback.reconciliation_variance, chargeback.unattributed_credits, chargeback.unattributed_share,
      cost.billed_credits, cost.by_team_credits.'
- tool_spec:
    type: sql_exec
    name: finops_chargeback_sql
    description: Execute a follow-up query against this product's published views only. Never against
      curated or raw schemas.
tool_resources:
  finops_chargeback_analyst:
    semantic_view: OBSERVABILITY.SEMANTIC.FINOPS_CHARGEBACK
  finops_chargeback_sql:
    execution_environment:
      type: warehouse
      warehouse: WH_SNOWOBS_AGENT
      query_timeout: 60
    max_rows: 1000
$$;
