-- Platform Cost & Attribution 1.1.0 — published views
--
-- Product: finops_chargeback · owner: finops-platform · classification: confidential
-- Freshness guarantee: 480 minutes (the slowest source behind this product).
--
-- Each view is the semantic layer's own compiled SQL for the metrics in
-- the product's boundary — the same query a dashboard tile runs, so a
-- consumer and a tile can never disagree about a figure (R1, R5).
--
-- The interactive row cap the SQL guard forces on ad-hoc execution is
-- deliberately absent here: a published relation is not truncated.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;
USE WAREHOUSE WH_SNOWOBS_APP;

-- V_FINOPS_CHARGEBACK_QUERY_EXECUTION: 9 columns · sources query_attribution_history, query_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION (
  TIME_BUCKET COMMENT 'Time bucket over STARTED_AT, at the coarsest grain the product''s metrics declare.',
  TEAM COMMENT 'Team from the query tag; UNATTRIBUTED when the tag is absent.',
  WAREHOUSE COMMENT 'Warehouse the query ran on.',
  DATABASE COMMENT 'Database context of the query.',
  ALLOCATION_METHOD COMMENT 'How the query''s credits reach a team — directly from its own tag, or via the residual pool spread pro-rata over tagged usage (HLD §10.2).',
  CHARGEBACK_ALLOCATED_CREDITS COMMENT 'Credits allocated to a team by its own query tags — the direct component of the three-part model (direct + idle share + cloud-services share, HLD §10.2). Read alone it under-states a team''s true cost, because idle time and cloud services are not attributable per query; it is the component that can be defended query by query, which is why it is stated separately. Unit: credits.',
  COST_BY_TEAM_CREDITS COMMENT 'Directly attributed credits by team, from the query tag. This is the direct component only — the full chargeback figure adds idle and cloud-services shares (see the allocation engine). Unit: credits.',
  CHARGEBACK_UNATTRIBUTED_CREDITS COMMENT 'Attributed credits carrying no team tag. This is the residual pool: it has to be spread over the tagged teams pro-rata, which means every credit here is a credit somebody is being charged for on an estimate rather than on evidence. Sliced by warehouse and user it becomes a tagging backlog. Unit: credits.',
  CHARGEBACK_UNATTRIBUTED_SHARE COMMENT 'Fraction of allocated credits that reached a team by estimate rather than by tag. It is the confidence figure that belongs next to every chargeback statement: at 5% the allocation is defensible, at 30% it is a negotiation.'
)
  COMMENT = 'Platform Cost & Attribution: Query execution. Grain: TIME_BUCKET, TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD. Freshness floor 480 minutes. Product finops_chargeback 1.1.0, owner finops-platform.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "STARTED_AT")
  ) AS "TIME_BUCKET",
  COALESCE(QUERY_TAG_TEAM, 'UNATTRIBUTED') AS "TEAM",
  WAREHOUSE_NAME AS "WAREHOUSE",
  DATABASE_NAME AS "DATABASE",
  CASE WHEN QUERY_TAG_TEAM IS NULL THEN 'RESIDUAL_POOL' ELSE 'DIRECT_TAG' END AS "ALLOCATION_METHOD",
  SUM(CREDITS_ATTRIBUTED) AS "CHARGEBACK_ALLOCATED_CREDITS",
  SUM(CREDITS_ATTRIBUTED) AS "COST_BY_TEAM_CREDITS",
  SUM(CASE WHEN QUERY_TAG_TEAM IS NULL THEN CREDITS_ATTRIBUTED ELSE 0 END) AS "CHARGEBACK_UNATTRIBUTED_CREDITS",
  (
    CAST(CASE
      WHEN (
        SUM(CREDITS_ATTRIBUTED)
      ) = 0 OR (
        SUM(CREDITS_ATTRIBUTED)
      ) IS NULL
      THEN NULL
      ELSE CAST((
        SUM(CASE WHEN QUERY_TAG_TEAM IS NULL THEN CREDITS_ATTRIBUTED ELSE 0 END)
      ) AS DECIMAL(38, 15)) / CAST((
        SUM(CREDITS_ATTRIBUTED)
      ) AS DECIMAL(38, 15))
    END AS DECIMAL(38, 15))
  ) AS "CHARGEBACK_UNATTRIBUTED_SHARE"
FROM (
  SELECT
    q."QUERY_ID" AS QUERY_ID,
    (
      TRY_TO_TIMESTAMP_NTZ(q."START_TIME")
    ) AS STARTED_AT,
    q."WAREHOUSE_NAME" AS WAREHOUSE_NAME,
    q."WAREHOUSE_SIZE" AS WAREHOUSE_SIZE,
    q."USER_NAME" AS USER_NAME,
    q."ROLE_NAME" AS ROLE_NAME,
    q."DATABASE_NAME" AS DATABASE_NAME,
    q."QUERY_TYPE" AS QUERY_TYPE,
    q."EXECUTION_STATUS" AS EXECUTION_STATUS,
    q."ERROR_CODE" AS ERROR_CODE,
    q."QUERY_PARAMETERIZED_HASH" AS FINGERPRINT,
    (
      JSON_EXTRACT_PATH_TEXT(q."QUERY_TAG", 'team')
    ) AS QUERY_TAG_TEAM,
    q."TOTAL_ELAPSED_TIME" AS ELAPSED_MS,
    q."COMPILATION_TIME" AS COMPILATION_MS,
    q."EXECUTION_TIME" AS EXECUTION_MS,
    q."QUEUED_OVERLOAD_TIME" AS QUEUED_OVERLOAD_MS,
    q."QUEUED_PROVISIONING_TIME" AS QUEUED_PROVISIONING_MS,
    q."BYTES_SCANNED" AS BYTES_SCANNED,
    q."BYTES_SPILLED_TO_LOCAL_STORAGE" AS BYTES_SPILLED_LOCAL,
    q."BYTES_SPILLED_TO_REMOTE_STORAGE" AS BYTES_SPILLED_REMOTE,
    q."PARTITIONS_SCANNED" AS PARTITIONS_SCANNED,
    q."PARTITIONS_TOTAL" AS PARTITIONS_TOTAL,
    q."PERCENTAGE_SCANNED_FROM_CACHE" AS CACHE_FRACTION,
    (
      CAST(COALESCE(a."CREDITS_ATTRIBUTED_COMPUTE", 0) AS DECIMAL(38, 9))
    ) AS CREDITS_ATTRIBUTED,
    (
      TRY_TO_TIMESTAMP_NTZ(q."_LOADED_AT")
    ) AS LANDED_AT /* Landing time: its gap from STARTED_AT is this platform's own freshness. */
  FROM query_history AS q
  LEFT JOIN query_attribution_history AS a
    ON a."QUERY_ID" = q."QUERY_ID"
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "STARTED_AT")
  ),
  COALESCE(QUERY_TAG_TEAM, 'UNATTRIBUTED'),
  WAREHOUSE_NAME,
  DATABASE_NAME,
  CASE WHEN QUERY_TAG_TEAM IS NULL THEN 'RESIDUAL_POOL' ELSE 'DIRECT_TAG' END;

-- V_FINOPS_CHARGEBACK_COST_DAILY: 4 columns · sources metering_daily_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY (
  TIME_BUCKET COMMENT 'Time bucket over USAGE_DAY, at the coarsest grain the product''s metrics declare.',
  SERVICE_TYPE COMMENT 'Snowflake service type (WAREHOUSE_METERING, SERVERLESS_TASK, AI_SERVICES, …).',
  CHARGEBACK_METERED_CREDITS COMMENT 'The account''s metered credits by service type — the control total every allocation must sum back to. It is stated in this domain, rather than borrowed from D1, because the reconciliation gate needs both sides of the comparison to carry the same provenance and the same latency floor. Unit: credits.',
  COST_BILLED_CREDITS COMMENT 'Credits actually billed — compute plus cloud services net of the daily 10% adjustment. This is the figure the chargeback reconciliation gate reconciles allocated cost against (R6). Unit: credits.'
)
  COMMENT = 'Platform Cost & Attribution: Cost by service type (daily). Grain: TIME_BUCKET, SERVICE_TYPE. Freshness floor 180 minutes. Product finops_chargeback 1.1.0, owner finops-platform.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "USAGE_DAY")
  ) AS "TIME_BUCKET",
  SERVICE_TYPE AS "SERVICE_TYPE",
  SUM(CREDITS_USED) AS "CHARGEBACK_METERED_CREDITS",
  SUM(CREDITS_BILLED) AS "COST_BILLED_CREDITS"
FROM (
  SELECT
    "SERVICE_TYPE" AS SERVICE_TYPE,
    CAST("USAGE_DATE" AS DATE) AS USAGE_DAY,
    (
      CAST("CREDITS_USED_COMPUTE" AS DECIMAL(38, 9))
    ) AS CREDITS_COMPUTE,
    (
      CAST("CREDITS_USED_CLOUD_SERVICES" AS DECIMAL(38, 9))
    ) AS CREDITS_CLOUD_SERVICES_RAW,
    (
      CAST("CREDITS_ADJUSTMENT_CLOUD_SERVICES" AS DECIMAL(38, 9))
    ) AS CREDITS_CLOUD_SERVICES_ADJUSTMENT,
    (
      CAST("CREDITS_USED_CLOUD_SERVICES" + "CREDITS_ADJUSTMENT_CLOUD_SERVICES" AS DECIMAL(38, 9))
    ) AS CREDITS_CLOUD_SERVICES_BILLED,
    (
      CAST("CREDITS_USED" AS DECIMAL(38, 9))
    ) AS CREDITS_USED,
    (
      CAST("CREDITS_BILLED" AS DECIMAL(38, 9))
    ) AS CREDITS_BILLED
  FROM metering_daily_history
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "USAGE_DAY")
  ),
  SERVICE_TYPE;

-- V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY: 3 columns · sources query_attribution_history, warehouse_metering_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY (
  TIME_BUCKET COMMENT 'Time bucket over METERING_HOUR, at the coarsest grain the product''s metrics declare.',
  WAREHOUSE COMMENT 'Warehouse the credits were metered against.',
  CHARGEBACK_RECONCILIATION_VARIANCE COMMENT 'Metered warehouse compute minus the compute attributable to individual queries. The gap is expected, not an error: QUERY_ATTRIBUTION_HISTORY excludes idle time, queries under about 100 ms, and Adaptive Warehouse jobs (ASSUMPTIONS §5). What the reconciliation gate checks is that the gap stays explainable — a variance that grows without idle time growing means the attribution view has stopped seeing part of the workload. Unit: credits.'
)
  COMMENT = 'Platform Cost & Attribution: Warehouse metering (hourly). Grain: TIME_BUCKET, WAREHOUSE. Freshness floor 480 minutes. Product finops_chargeback 1.1.0, owner finops-platform.'
AS
SELECT
  (
    DATE_TRUNC('HOUR', "METERING_HOUR")
  ) AS "TIME_BUCKET",
  WAREHOUSE_NAME AS "WAREHOUSE",
  SUM(CREDITS_COMPUTE) - SUM(CREDITS_ATTRIBUTED) AS "CHARGEBACK_RECONCILIATION_VARIANCE"
FROM (
  SELECT
    m."WAREHOUSE_NAME" AS WAREHOUSE_NAME,
    m."WAREHOUSE_ID" AS WAREHOUSE_ID,
    (
      DATE_TRUNC('HOUR', (
        TRY_TO_TIMESTAMP_NTZ(m."START_TIME")
      ))
    ) AS METERING_HOUR,
    (
      CAST(m."CREDITS_USED_COMPUTE" AS DECIMAL(38, 9))
    ) AS CREDITS_COMPUTE,
    (
      CAST(m."CREDITS_USED_CLOUD_SERVICES" AS DECIMAL(38, 9))
    ) AS CREDITS_CLOUD_SERVICES,
    (
      CAST(COALESCE(a.CREDITS_ATTRIBUTED, 0) AS DECIMAL(38, 9))
    ) AS CREDITS_ATTRIBUTED,
    (
      CAST(m."CREDITS_USED_COMPUTE" - COALESCE(a.CREDITS_ATTRIBUTED, 0) AS DECIMAL(38, 9))
    ) AS CREDITS_IDLE,
    r.WAREHOUSE_RANK AS WAREHOUSE_RANK /* Whole-window rank by total compute, so concentration metrics can ask for */ /* "the top N warehouses" without a correlated subquery per row. */
  FROM warehouse_metering_history AS m
  LEFT JOIN (
    SELECT
      "WAREHOUSE_NAME" AS WAREHOUSE_NAME,
      (
        DATE_TRUNC('HOUR', (
          TRY_TO_TIMESTAMP_NTZ("START_TIME")
        ))
      ) AS ATTRIBUTION_HOUR,
      SUM((
        CAST("CREDITS_ATTRIBUTED_COMPUTE" AS DECIMAL(38, 9))
      )) AS CREDITS_ATTRIBUTED
    FROM query_attribution_history
    GROUP BY
      1,
      2
  ) AS a
    ON a.WAREHOUSE_NAME = m."WAREHOUSE_NAME"
    AND a.ATTRIBUTION_HOUR = (
      DATE_TRUNC('HOUR', (
        TRY_TO_TIMESTAMP_NTZ(m."START_TIME")
      ))
    )
  LEFT JOIN (
    SELECT
      "WAREHOUSE_NAME" AS WAREHOUSE_NAME,
      DENSE_RANK() OVER (ORDER BY SUM("CREDITS_USED_COMPUTE") DESC NULLS LAST) AS WAREHOUSE_RANK
    FROM warehouse_metering_history
    GROUP BY
      1
  ) AS r
    ON r.WAREHOUSE_NAME = m."WAREHOUSE_NAME"
) AS base
GROUP BY
  (
    DATE_TRUNC('HOUR', "METERING_HOUR")
  ),
  WAREHOUSE_NAME;
