-- Platform Cost & Attribution 1.1.0 — semantic view
--
-- Cortex Analyst reads this view to answer questions about the product.
-- 14 verified queries teach it the team's vocabulary.
--
-- Additive measures are METRICS; ratios, percentiles, and distinct counts
-- are FACTS, because re-aggregating them would produce a wrong number.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE SEMANTIC VIEW OBSERVABILITY.SEMANTIC.FINOPS_CHARGEBACK
  TABLES (
    finops_chargeback_query_execution AS OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
      PRIMARY KEY (TIME_BUCKET, TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD)
      COMMENT = 'Platform Cost & Attribution: Query execution.',
    finops_chargeback_cost_daily AS OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY
      PRIMARY KEY (TIME_BUCKET, SERVICE_TYPE)
      COMMENT = 'Platform Cost & Attribution: Cost by service type (daily).',
    finops_chargeback_warehouse_metering_hourly AS OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY
      PRIMARY KEY (TIME_BUCKET, WAREHOUSE)
      COMMENT = 'Platform Cost & Attribution: Warehouse metering (hourly).'
  )
  FACTS (
    finops_chargeback_query_execution.CHARGEBACK_UNATTRIBUTED_SHARE AS CHARGEBACK_UNATTRIBUTED_SHARE
      WITH SYNONYMS = ('allocation confidence', 'estimate share', 'unattributed share of allocation', 'untagged percentage')
      COMMENT = 'Fraction of allocated credits that reached a team by estimate rather than by tag. It is the confidence figure that belongs next to every chargeback statement: at 5% the allocation is defensible, at 30% it is a negotiation. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.'
  )
  DIMENSIONS (
    finops_chargeback_query_execution.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over STARTED_AT, at the coarsest grain the product''s metrics declare.',
    finops_chargeback_query_execution.TEAM AS TEAM
      WITH SYNONYMS = ('team')
      COMMENT = 'Team from the query tag; UNATTRIBUTED when the tag is absent.',
    finops_chargeback_query_execution.WAREHOUSE AS WAREHOUSE
      WITH SYNONYMS = ('warehouse')
      COMMENT = 'Warehouse the query ran on.',
    finops_chargeback_query_execution.DATABASE AS DATABASE
      WITH SYNONYMS = ('database')
      COMMENT = 'Database context of the query.',
    finops_chargeback_query_execution.ALLOCATION_METHOD AS ALLOCATION_METHOD
      WITH SYNONYMS = ('allocation method')
      COMMENT = 'How the query''s credits reach a team — directly from its own tag, or via the residual pool spread pro-rata over tagged usage (HLD §10.2).',
    finops_chargeback_cost_daily.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over USAGE_DAY, at the coarsest grain the product''s metrics declare.',
    finops_chargeback_cost_daily.SERVICE_TYPE AS SERVICE_TYPE
      WITH SYNONYMS = ('service type')
      COMMENT = 'Snowflake service type (WAREHOUSE_METERING, SERVERLESS_TASK, AI_SERVICES, …).',
    finops_chargeback_warehouse_metering_hourly.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over METERING_HOUR, at the coarsest grain the product''s metrics declare.',
    finops_chargeback_warehouse_metering_hourly.WAREHOUSE AS WAREHOUSE
      WITH SYNONYMS = ('warehouse')
      COMMENT = 'Warehouse the credits were metered against.'
  )
  METRICS (
    finops_chargeback_query_execution.CHARGEBACK_ALLOCATED_CREDITS AS SUM(CHARGEBACK_ALLOCATED_CREDITS)
      WITH SYNONYMS = ('allocated cost', 'allocated credits by team (direct)', 'chargeback', 'showback', 'team allocation')
      COMMENT = 'Credits allocated to a team by its own query tags — the direct component of the three-part model (direct + idle share + cloud-services share, HLD §10.2). Read alone it under-states a team''s true cost, because idle time and cloud services are not attributable per query; it is the component that can be defended query by query, which is why it is stated separately.',
    finops_chargeback_query_execution.COST_BY_TEAM_CREDITS AS SUM(COST_BY_TEAM_CREDITS)
      WITH SYNONYMS = ('cost by team', 'credits by team (direct)', 'departmental cost', 'team spend')
      COMMENT = 'Directly attributed credits by team, from the query tag. This is the direct component only — the full chargeback figure adds idle and cloud-services shares (see the allocation engine).',
    finops_chargeback_query_execution.CHARGEBACK_UNATTRIBUTED_CREDITS AS SUM(CHARGEBACK_UNATTRIBUTED_CREDITS)
      WITH SYNONYMS = ('residual pool', 'unallocated spend', 'unattributed credits', 'untagged credits')
      COMMENT = 'Attributed credits carrying no team tag. This is the residual pool: it has to be spread over the tagged teams pro-rata, which means every credit here is a credit somebody is being charged for on an estimate rather than on evidence. Sliced by warehouse and user it becomes a tagging backlog.',
    finops_chargeback_cost_daily.CHARGEBACK_METERED_CREDITS AS SUM(CHARGEBACK_METERED_CREDITS)
      WITH SYNONYMS = ('control total', 'metered credits (reconciliation control total)', 'metered total', 'what the account actually used')
      COMMENT = 'The account''s metered credits by service type — the control total every allocation must sum back to. It is stated in this domain, rather than borrowed from D1, because the reconciliation gate needs both sides of the comparison to carry the same provenance and the same latency floor.',
    finops_chargeback_cost_daily.COST_BILLED_CREDITS AS SUM(COST_BILLED_CREDITS)
      WITH SYNONYMS = ('billed credits', 'chargeable credits', 'net credits')
      COMMENT = 'Credits actually billed — compute plus cloud services net of the daily 10% adjustment. This is the figure the chargeback reconciliation gate reconciles allocated cost against (R6).',
    finops_chargeback_warehouse_metering_hourly.CHARGEBACK_RECONCILIATION_VARIANCE AS SUM(CHARGEBACK_RECONCILIATION_VARIANCE)
      WITH SYNONYMS = ('allocation residual', 'reconciliation gap', 'reconciliation variance (metered minus allocated)', 'unallocated compute')
      COMMENT = 'Metered warehouse compute minus the compute attributable to individual queries. The gap is expected, not an error: QUERY_ATTRIBUTION_HISTORY excludes idle time, queries under about 100 ms, and Adaptive Warehouse jobs (ASSUMPTIONS §5). What the reconciliation gate checks is that the gap stays explainable — a variance that grows without idle time growing means the attribution view has stopped seeing part of the workload.'
  )
  COMMENT = 'Fully allocated Snowflake cost by team, warehouse, and database, alongside the metered and billed account totals the allocation reconciles against. Direct attributed compute, unattributed spend, and the reconciliation variance are published together so a chargeback figure is never read without the evidence that it reconciles (R6). Deliberately credit-denominated: spend in contract currency comes from ORGANIZATION_USAGE, which documents 72 hours of latency, and folding it in here would drag this product''s whole freshness guarantee from eight hours to three days for every consumer.'
  AI_VERIFIED_QUERIES (
    vq_chargeback_allocated_credits_1 AS (
      QUESTION 'allocated credits by team'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(CHARGEBACK_ALLOCATED_CREDITS) AS CHARGEBACK_ALLOCATED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY CHARGEBACK_ALLOCATED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_allocated_credits_2 AS (
      QUESTION 'chargeback for TEAM_DATA_ENG'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(CHARGEBACK_ALLOCATED_CREDITS) AS CHARGEBACK_ALLOCATED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY CHARGEBACK_ALLOCATED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_cost_by_team_credits_1 AS (
      QUESTION 'credits by team this month'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(COST_BY_TEAM_CREDITS) AS COST_BY_TEAM_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY COST_BY_TEAM_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_cost_by_team_credits_2 AS (
      QUESTION 'which team spent the most last week'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(COST_BY_TEAM_CREDITS) AS COST_BY_TEAM_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY COST_BY_TEAM_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_unattributed_credits_1 AS (
      QUESTION 'unattributed credits by warehouse'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(CHARGEBACK_UNATTRIBUTED_CREDITS) AS CHARGEBACK_UNATTRIBUTED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY CHARGEBACK_UNATTRIBUTED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_unattributed_credits_2 AS (
      QUESTION 'who is not tagging their queries'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, SUM(CHARGEBACK_UNATTRIBUTED_CREDITS) AS CHARGEBACK_UNATTRIBUTED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD
ORDER BY CHARGEBACK_UNATTRIBUTED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_unattributed_share_1 AS (
      QUESTION 'how much of the allocation is estimated'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TIME_BUCKET, TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, CHARGEBACK_UNATTRIBUTED_SHARE
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY CHARGEBACK_UNATTRIBUTED_SHARE DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_unattributed_share_2 AS (
      QUESTION 'unattributed share by warehouse'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT TIME_BUCKET, TEAM, WAREHOUSE, DATABASE, ALLOCATION_METHOD, CHARGEBACK_UNATTRIBUTED_SHARE
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_QUERY_EXECUTION
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY CHARGEBACK_UNATTRIBUTED_SHARE DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_metered_credits_1 AS (
      QUESTION 'metered credits by service type'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT SERVICE_TYPE, SUM(CHARGEBACK_METERED_CREDITS) AS CHARGEBACK_METERED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY SERVICE_TYPE
ORDER BY CHARGEBACK_METERED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_metered_credits_2 AS (
      QUESTION 'control total for reconciliation'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT SERVICE_TYPE, SUM(CHARGEBACK_METERED_CREDITS) AS CHARGEBACK_METERED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY SERVICE_TYPE
ORDER BY CHARGEBACK_METERED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_cost_billed_credits_1 AS (
      QUESTION 'billed credits this month'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT SERVICE_TYPE, SUM(COST_BILLED_CREDITS) AS COST_BILLED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY SERVICE_TYPE
ORDER BY COST_BILLED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_cost_billed_credits_2 AS (
      QUESTION 'billed credits by day'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT SERVICE_TYPE, SUM(COST_BILLED_CREDITS) AS COST_BILLED_CREDITS
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_COST_DAILY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY SERVICE_TYPE
ORDER BY COST_BILLED_CREDITS DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_reconciliation_variance_1 AS (
      QUESTION 'reconciliation variance by warehouse'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT WAREHOUSE, SUM(CHARGEBACK_RECONCILIATION_VARIANCE) AS CHARGEBACK_RECONCILIATION_VARIANCE
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY WAREHOUSE
ORDER BY CHARGEBACK_RECONCILIATION_VARIANCE DESC NULLS LAST
LIMIT 20'
    ),
    vq_chargeback_reconciliation_variance_2 AS (
      QUESTION 'unallocated compute credits'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = finops-platform@internal)'
      SQL 'SELECT WAREHOUSE, SUM(CHARGEBACK_RECONCILIATION_VARIANCE) AS CHARGEBACK_RECONCILIATION_VARIANCE
FROM OBSERVABILITY.PUBLISHED.V_FINOPS_CHARGEBACK_WAREHOUSE_METERING_HOURLY
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY WAREHOUSE
ORDER BY CHARGEBACK_RECONCILIATION_VARIANCE DESC NULLS LAST
LIMIT 20'
    )
  )
;
