-- Observability & FinOps Platform — data product foundations
--
-- Creates the database, schemas, warehouses, and consumer roles that
-- published data products land in. Idempotent: safe to re-run.
--
-- Run as a role that can create databases, warehouses, and roles.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS OBSERVABILITY
  COMMENT = 'Published observability data products';
CREATE SCHEMA IF NOT EXISTS OBSERVABILITY.PUBLISHED
  COMMENT = 'Secure views consumers read';
CREATE SCHEMA IF NOT EXISTS OBSERVABILITY.SEMANTIC
  COMMENT = 'Semantic views for Cortex Analyst';
CREATE SCHEMA IF NOT EXISTS OBSERVABILITY.SEARCH
  COMMENT = 'Cortex Search services over product text columns';
CREATE SCHEMA IF NOT EXISTS OBSERVABILITY.AGENT
  COMMENT = 'Cortex Agents scoped to a single data product';

-- Agent traffic runs on its own small, resource-monitored warehouse so a
-- conversational workload cannot consume refresh capacity (§14).
CREATE WAREHOUSE IF NOT EXISTS WH_SNOWOBS_AGENT
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Cortex Agent serving warehouse for observability data products';

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS SNOWOBS_CONSUMER
  COMMENT = 'Reads published observability data products';
CREATE ROLE IF NOT EXISTS SNOWOBS_AGENT_USER
  COMMENT = 'Talks to observability data product agents';

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE OBSERVABILITY TO ROLE SNOWOBS_CONSUMER;
GRANT USAGE ON SCHEMA OBSERVABILITY.PUBLISHED TO ROLE SNOWOBS_CONSUMER;
GRANT USAGE ON WAREHOUSE WH_SNOWOBS_AGENT TO ROLE SNOWOBS_AGENT_USER;
