"""Artifact emitters (BUILD_PROMPT §13.4).

Every emitter is a pure function from ``(product, contract, target)`` to text.
No emitter connects to anything, writes a file, or reads the clock: the same
inputs always produce byte-identical output, which is what makes the golden
files in ``tests/golden/`` a real regression gate rather than a formality.

Nothing here executes. These artifacts are what a human reviews and runs in
their own account after an approval is recorded (R2, R8).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from snowobs_common.errors import AppError

#: Snowflake identifiers we are willing to interpolate. Everything reaching an
#: emitter comes from a validated slug, an uppercased contract column, or the
#: deployment target below — but the check is cheap and the failure mode is not.
_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")

#: Blanket privileges that must never appear in generated SQL (§27.3).
FORBIDDEN_GRANTS = ("IMPORTED PRIVILEGES", "ACCOUNTADMIN", "SECURITYADMIN", "ALL PRIVILEGES")


class EmitterError(AppError):
    status_code = 400
    title = "Artifact could not be generated"
    problem_type = "https://snowobs.dev/problems/artifact-emitter"


@dataclass(frozen=True)
class SnowflakeTarget:
    """Where a published product lands. Deployment configuration, never code.

    Defaults line up with the publisher role generated by
    ``snowobs_live.provisioning``: one database, a ``PUBLISHED`` schema for the
    secure views, and separate schemas for the semantic view, the search
    service, and the agent so each can be granted independently.
    """

    #: The Snowflake account these artifacts are published into. A published
    #: view runs inside one account, so the account column its query carries is
    #: that account — known here as deployment configuration rather than read
    #: from the data, because `ACCOUNT_USAGE` has no account column to read.
    #: Left unset, the column renders NULL: honest about not knowing, rather
    #: than attributing the rows to a guess.
    account: str | None = None

    database: str = "OBSERVABILITY"
    published_schema: str = "PUBLISHED"
    semantic_schema: str = "SEMANTIC"
    search_schema: str = "SEARCH"
    agent_schema: str = "AGENT"
    #: Warehouse the published objects are built and refreshed on.
    warehouse: str = "WH_SNOWOBS_APP"
    #: Separate, resource-monitored warehouse for agent traffic, so a chatty
    #: agent cannot consume the platform's own refresh capacity.
    agent_warehouse: str = "WH_SNOWOBS_AGENT"
    publisher_role: str = "SNOWOBS_PUBLISHER"
    consumer_role: str = "SNOWOBS_CONSUMER"
    agent_role: str = "SNOWOBS_AGENT_USER"
    #: Accounts the organization listing is offered to. Empty means the whole
    #: organization.
    organization_accounts: tuple[str, ...] = ()
    #: Regions the listing is fulfilled into. Empty means the provider region only.
    access_regions: tuple[str, ...] = ()
    #: Orchestration model for the agent spec. ``None`` leaves the account
    #: default in place rather than pinning a model identifier we cannot verify
    #: against the customer's region (ASSUMPTIONS U-4).
    orchestration_model: str | None = None
    #: Ceiling on one agent turn, in seconds and tokens.
    orchestration_budget_seconds: int = 120
    orchestration_budget_tokens: int = 32_000
    #: Statement timeout applied to the agent's constrained SQL tool.
    agent_query_timeout_seconds: int = 60

    def qualified(self, schema: str, name: str) -> str:
        return f"{ident(self.database)}.{ident(schema)}.{ident(name)}"

    def view(self, name: str) -> str:
        return self.qualified(self.published_schema, name)


def ident(name: str) -> str:
    """Validate an identifier before it is interpolated into generated SQL."""
    if not _IDENTIFIER.match(name):
        raise EmitterError(f"unsafe SQL identifier: {name!r}")
    return name


def literal(value: str) -> str:
    """A single-quoted SQL string literal with embedded quotes doubled."""
    return "'" + value.replace("'", "''") + "'"


def one_line(text: str) -> str:
    """Collapse a YAML block scalar to a single line for a SQL comment."""
    return " ".join(text.split())


def header(title: str, lines: list[str]) -> str:
    """The standard preamble on every generated script.

    The platform never runs these. Saying so at the top of the file is part of
    the artifact, not decoration: the operator reading it is the control.
    """
    body = [f"-- {title}", "--"]
    body.extend(f"-- {line}" if line else "--" for line in lines)
    body.extend(
        [
            "--",
            "-- Generated by the Observability & FinOps Platform. Review before running.",
            "-- The platform does not execute this script; a human does (R2, R8).",
            "",
        ]
    )
    return "\n".join(body)


def audit_generated_sql(sql: str) -> list[str]:
    """Return any §27.3 violations found in generated SQL. Empty means clean."""
    problems: list[str] = []
    for line in sql.splitlines():
        stripped = line.strip()
        if stripped.startswith("--"):
            continue  # a comment naming a role is not a grant of it
        upper = stripped.upper()
        if not upper.startswith("GRANT "):
            continue
        for forbidden in FORBIDDEN_GRANTS:
            if forbidden in upper:
                problems.append(f"generated SQL grants {forbidden}: {stripped}")
    return problems


def indent(text: str, spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join(f"{pad}{line}" if line.strip() else line for line in text.splitlines())
