-- Security & Access Governance 1.0.0 — Cortex Agent
--
-- One agent per data product. It can reach this product's semantic view,
-- its search service, and its published views — nothing else.
--
-- Surfaced in Snowflake Intelligence to any role holding USAGE on the
-- agent; grants are in the grants script.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).
USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE AGENT OBSERVABILITY.AGENT.ACCESS_GOVERNANCE_AGENT
  COMMENT = 'Conversational interface to Security & Access Governance 1.0.0. Scoped to the product''s semantic view; quotes tool results only.'
  PROFILE = '{"display_name": "Security & Access Governance Copilot"}'
  FROM SPECIFICATION $$
orchestration:
  budget:
    seconds: 120
    tokens: 32000
instructions:
  response: 'You answer questions about Security & Access Governance, an observability data product owned
    by security-engineering. Scope: V_ACCESS_GOVERNANCE_LOGIN, V_ACCESS_GOVERNANCE_GRANT, V_ACCESS_GOVERNANCE_USER.
    Every number you state must come from a tool result. Never compute, estimate, extrapolate, or round
    a figure yourself; if a tool did not return it, say you cannot ground the claim and offer the question
    you could answer instead. State the time range and the as-of point of every figure. This product''s
    freshness guarantee is 120 minutes, which is the documented latency of its slowest source: never imply
    a figure is fresher than that, and say so when a user asks about the last hour. A null is not a zero.
    If a measure is null, report it as unknown for that slice and explain why, rather than reporting no
    activity. Cite the relation and the governed metric behind each figure so the user can check it. Answer
    only from this product; if a question needs data outside V_ACCESS_GOVERNANCE_LOGIN, V_ACCESS_GOVERNANCE_GRANT,
    V_ACCESS_GOVERNANCE_USER, say which product would have it.'
  orchestration: Decompose the question first. If it asks how much, how many, a trend, or a comparison,
    use the analyst tool over the semantic view. If the question asks which specific error_class values
    match a description, use the search tool. Use the SQL tool only to follow up on a result the analyst
    tool already returned, and only against this product's published views. Never invent a dimension value.
    If a filter value does not appear in the data, say so rather than returning an empty result as if
    it were zero. If a question is ambiguous between two slices, ask which one before answering.
  sample_questions:
  - question: users with the most failed logins
  - question: failed login rate this week
  - question: who still logs in without MFA
  - question: users logging in from many IPs
  - question: who has ACCOUNTADMIN
  - question: new grants this week
tools:
- tool_spec:
    type: cortex_analyst_text_to_sql
    name: access_governance_analyst
    description: 'Answer aggregate, trend, and comparison questions about Security & Access Governance
      from its governed semantic view. Covers 9 metrics: sec.disabled_but_granted_users, sec.distinct_client_ips,
      sec.dormant_users, sec.failed_login_rate, sec.failed_logins, sec.new_grants, sec.privileged_grants,
      sec.single_factor_logins, sec.users_without_key_pair.'
- tool_spec:
    type: cortex_search
    name: access_governance_search
    description: Find specific error_class values by free text. Use when the question is about which particular
      items match a description, rather than how many there are.
- tool_spec:
    type: sql_exec
    name: access_governance_sql
    description: Execute a follow-up query against this product's published views only. Never against
      curated or raw schemas.
tool_resources:
  access_governance_analyst:
    semantic_view: OBSERVABILITY.SEMANTIC.ACCESS_GOVERNANCE
  access_governance_search:
    name: OBSERVABILITY.SEARCH.ACCESS_GOVERNANCE_ERROR_CLASS
    max_results: 10
    title_column: ERROR_CLASS
  access_governance_sql:
    execution_environment:
      type: warehouse
      warehouse: WH_SNOWOBS_AGENT
      query_timeout: 60
    max_rows: 1000
$$;
