-- Security & Access Governance 1.0.0 — Cortex Search service
--
-- Indexes ERROR_CLASS from V_ACCESS_GOVERNANCE_LOGIN over a 90-day window.
--
-- Only columns the contract marks searchable are indexed. Sensitive
-- columns and query text are never indexed (R2, §12.5).
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).
USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE CORTEX SEARCH SERVICE OBSERVABILITY.SEARCH.ACCESS_GOVERNANCE_ERROR_CLASS
  ON ERROR_CLASS
  ATTRIBUTES CLIENT_TYPE, FIRST_FACTOR
  WAREHOUSE = WH_SNOWOBS_APP
  TARGET_LAG = '4 hours'
  COMMENT = 'Free-text search over ERROR_CLASS in V_ACCESS_GOVERNANCE_LOGIN for Security & Access Governance 1.0.0. Indexed window: 90 days.'
  AS (
    SELECT ERROR_CLASS, CLIENT_TYPE, FIRST_FACTOR
      FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
      WHERE TIME_BUCKET >= DATEADD(day, -90, CURRENT_DATE())
        AND ERROR_CLASS IS NOT NULL
  );
