-- Security & Access Governance 1.0.0 — published views
--
-- Product: access_governance · owner: security-engineering · classification: restricted
-- Freshness guarantee: 120 minutes (the slowest source behind this product).
--
-- Each view is the semantic layer's own compiled SQL for the metrics in
-- the product's boundary — the same query a dashboard tile runs, so a
-- consumer and a tile can never disagree about a figure (R1, R5).
--
-- The interactive row cap the SQL guard forces on ad-hoc execution is
-- deliberately absent here: a published relation is not truncated.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;
USE WAREHOUSE WH_SNOWOBS_APP;

-- V_ACCESS_GOVERNANCE_LOGIN: 10 columns · sources login_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN (
  TIME_BUCKET COMMENT 'Time bucket over EVENT_AT, at the coarsest grain the product''s metrics declare.',
  USER COMMENT 'User the attempt was made against.',
  CLIENT_TYPE COMMENT 'Reported driver or client (JDBC, PYTHON_DRIVER, SNOWFLAKE_UI, …).',
  FIRST_FACTOR COMMENT 'First authentication factor (PASSWORD, RSA_KEYPAIR, OAUTH, …).',
  ERROR_CLASS COMMENT 'Snowflake error code of a failed attempt, or NONE.',
  CLIENT_IP COMMENT 'Source IP of the attempt.',
  SEC_FAILED_LOGINS COMMENT 'Count of failed authentication attempts. Per user and per source IP this is the shape a credential-stuffing attempt makes: many failures against many users from few addresses, or many failures against one user from many.',
  SEC_FAILED_LOGIN_RATE COMMENT 'Share of authentication attempts that failed. A background rate of a few percent is normal — mistyped passwords, expired sessions. A step change on one user or one client type is not, and that is what the slice is for.',
  SEC_SINGLE_FACTOR_LOGINS COMMENT 'Successful logins that presented no second authentication factor. Snowflake blocks single-factor password sign-in from October 2026, so this is a migration burn-down: every login counted here is one that will stop working. Key-pair service authentication legitimately has no second factor and shows up here too — slice by first_factor to separate the two populations.',
  SEC_DISTINCT_CLIENT_IPS COMMENT 'Number of distinct source addresses a user authenticated from. A service account pinned to a network allowlist should be a small constant; a jump is either an infrastructure change nobody mentioned or a credential in the wrong hands.'
)
  COMMENT = 'Security & Access Governance: Login attempt. Grain: TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP. Freshness floor 120 minutes. Product access_governance 1.0.0, owner security-engineering.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "EVENT_AT")
  ) AS "TIME_BUCKET",
  USER_NAME AS "USER",
  COALESCE(CLIENT_TYPE, 'UNKNOWN') AS "CLIENT_TYPE",
  COALESCE(FIRST_AUTH_FACTOR, 'UNKNOWN') AS "FIRST_FACTOR",
  COALESCE(ERROR_CODE, 'NONE') AS "ERROR_CLASS",
  COALESCE(CLIENT_IP, 'UNKNOWN') AS "CLIENT_IP",
  SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) AS "SEC_FAILED_LOGINS",
  (
    CAST(CASE
      WHEN (
        COUNT(*)
      ) = 0 OR (
        COUNT(*)
      ) IS NULL
      THEN NULL
      ELSE CAST((
        SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END)
      ) AS DECIMAL(38, 15)) / CAST((
        COUNT(*)
      ) AS DECIMAL(38, 15))
    END AS DECIMAL(38, 15))
  ) AS "SEC_FAILED_LOGIN_RATE",
  SUM(CASE WHEN IS_SUCCESS = 'YES' AND SECOND_AUTH_FACTOR IS NULL THEN 1 ELSE 0 END) AS "SEC_SINGLE_FACTOR_LOGINS",
  COUNT(DISTINCT CLIENT_IP) AS "SEC_DISTINCT_CLIENT_IPS"
FROM (
  SELECT
    "EVENT_ID" AS EVENT_ID,
    (
      TRY_TO_TIMESTAMP_NTZ("EVENT_TIMESTAMP")
    ) AS EVENT_AT,
    "EVENT_TYPE" AS EVENT_TYPE,
    "USER_NAME" AS USER_NAME,
    "CLIENT_IP" AS CLIENT_IP,
    "REPORTED_CLIENT_TYPE" AS CLIENT_TYPE,
    "REPORTED_CLIENT_VERSION" AS CLIENT_VERSION,
    "FIRST_AUTHENTICATION_FACTOR" AS FIRST_AUTH_FACTOR,
    "SECOND_AUTHENTICATION_FACTOR" AS SECOND_AUTH_FACTOR,
    "IS_SUCCESS" AS IS_SUCCESS,
    "ERROR_CODE" AS ERROR_CODE,
    "ERROR_MESSAGE" AS ERROR_MESSAGE
  FROM login_history
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "EVENT_AT")
  ),
  USER_NAME,
  COALESCE(CLIENT_TYPE, 'UNKNOWN'),
  COALESCE(FIRST_AUTH_FACTOR, 'UNKNOWN'),
  COALESCE(ERROR_CODE, 'NONE'),
  COALESCE(CLIENT_IP, 'UNKNOWN');

-- V_ACCESS_GOVERNANCE_GRANT: 9 columns · sources grants_to_users, users
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT (
  TIME_BUCKET COMMENT 'Time bucket over GRANTED_AT, at the coarsest grain the product''s metrics declare.',
  ROLE COMMENT 'Role granted.',
  GRANTEE COMMENT 'User the role was granted to.',
  GRANTED_BY COMMENT 'Role that issued the grant.',
  GRANTEE_TYPE COMMENT 'PERSON, SERVICE, or LEGACY_SERVICE.',
  PRIVILEGE_TIER COMMENT 'PRIVILEGED for the account-administration roles, STANDARD otherwise.',
  SEC_PRIVILEGED_GRANTS COMMENT 'Live grants of ACCOUNTADMIN, SECURITYADMIN, or ORGADMIN. These roles can change billing, read every object, and rewrite the access model, so the right number is small, known, and unchanging — and any movement in it should be traceable to a ticket. Revoked grants are excluded so the figure is current holdings rather than everything ever granted.',
  SEC_NEW_GRANTS COMMENT 'Grants created inside the requested window, from GRANTS_TO_USERS.CREATED_ON. This is the privilege-drift feed: a review reads it in date order and asks who approved each row. Sliced by privilege_tier it separates routine team membership from a new administrator.',
  SEC_DISABLED_BUT_GRANTED_USERS COMMENT 'Disabled accounts that still hold live role grants. Disabling a user stops them logging in but leaves the grant graph untouched, so this is the deprovisioning tail: the difference between "cannot sign in today" and "has no access", which is the difference that matters if the account is ever re-enabled.'
)
  COMMENT = 'Security & Access Governance: Role grant to user. Grain: TIME_BUCKET, ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER. Freshness floor 120 minutes. Product access_governance 1.0.0, owner security-engineering.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "GRANTED_AT")
  ) AS "TIME_BUCKET",
  ROLE_NAME AS "ROLE",
  GRANTEE_NAME AS "GRANTEE",
  COALESCE(GRANTED_BY, 'UNKNOWN') AS "GRANTED_BY",
  COALESCE(GRANTEE_TYPE, 'UNKNOWN') AS "GRANTEE_TYPE",
  CASE
    WHEN ROLE_NAME IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'ORGADMIN')
    THEN 'PRIVILEGED'
    ELSE 'STANDARD'
  END AS "PRIVILEGE_TIER",
  SUM(
    CASE
      WHEN ROLE_NAME IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'ORGADMIN') AND REVOKED_AT IS NULL
      THEN 1
      ELSE 0
    END
  ) AS "SEC_PRIVILEGED_GRANTS",
  COUNT(*) AS "SEC_NEW_GRANTS",
  COUNT(DISTINCT CASE WHEN GRANTEE_DISABLED AND REVOKED_AT IS NULL THEN GRANTEE_NAME END) AS "SEC_DISABLED_BUT_GRANTED_USERS"
FROM (
  SELECT
    g."ROLE" AS ROLE_NAME,
    g."GRANTED_TO" AS GRANTED_TO,
    g."GRANTEE_NAME" AS GRANTEE_NAME,
    g."GRANTED_BY" AS GRANTED_BY,
    (
      TRY_TO_TIMESTAMP_NTZ(g."CREATED_ON")
    ) AS GRANTED_AT,
    (
      TRY_TO_TIMESTAMP_NTZ(g."DELETED_ON")
    ) AS REVOKED_AT,
    COALESCE(u."DISABLED", FALSE) AS GRANTEE_DISABLED,
    u."TYPE" AS GRANTEE_TYPE,
    (
      TRY_TO_TIMESTAMP_NTZ(u."LAST_SUCCESS_LOGIN")
    ) AS GRANTEE_LAST_LOGIN_AT
  FROM grants_to_users AS g
  LEFT JOIN users AS u
    ON u."NAME" = g."GRANTEE_NAME"
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "GRANTED_AT")
  ),
  ROLE_NAME,
  GRANTEE_NAME,
  COALESCE(GRANTED_BY, 'UNKNOWN'),
  COALESCE(GRANTEE_TYPE, 'UNKNOWN'),
  CASE
    WHEN ROLE_NAME IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'ORGADMIN')
    THEN 'PRIVILEGED'
    ELSE 'STANDARD'
  END;

-- V_ACCESS_GOVERNANCE_USER: 7 columns · sources users
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER (
  USER COMMENT 'User name.',
  USER_TYPE COMMENT 'PERSON, SERVICE, or LEGACY_SERVICE.',
  DEFAULT_ROLE COMMENT 'Role the user assumes on connect when none is specified.',
  ACCOUNT_STATUS COMMENT 'Whether the user is currently disabled.',
  CREDENTIAL_TYPE COMMENT 'Credentials configured on the user — the key-pair rollout view.',
  SEC_DORMANT_USERS COMMENT 'Enabled users with no successful login in 90 days. Every one is a live credential with no owner watching it — the cheapest access risk to remove and the one most often left alone because nobody is sure who it belongs to. Age is measured against the newest login in the snapshot, so the cohort is stable between runs.',
  SEC_USERS_WITHOUT_KEY_PAIR COMMENT 'Enabled users with no RSA public key configured. Sliced by user_type this is the key-pair rollout backlog for service accounts, which cannot use interactive MFA and must move to key-pair authentication before password sign-in is blocked.'
)
  COMMENT = 'Security & Access Governance: User. Grain: USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE. Freshness floor 120 minutes. Product access_governance 1.0.0, owner security-engineering.'
AS
SELECT
  USER_NAME AS "USER",
  COALESCE(USER_TYPE, 'UNKNOWN') AS "USER_TYPE",
  COALESCE(DEFAULT_ROLE, 'NONE') AS "DEFAULT_ROLE",
  CASE WHEN IS_DISABLED THEN 'DISABLED' ELSE 'ACTIVE' END AS "ACCOUNT_STATUS",
  CASE
    WHEN HAS_RSA_PUBLIC_KEY AND HAS_PASSWORD
    THEN 'KEY_AND_PASSWORD'
    WHEN HAS_RSA_PUBLIC_KEY
    THEN 'KEY_PAIR'
    WHEN HAS_PASSWORD
    THEN 'PASSWORD_ONLY'
    ELSE 'FEDERATED_OR_NONE'
  END AS "CREDENTIAL_TYPE",
  COUNT(
    DISTINCT CASE WHEN DAYS_SINCE_LAST_LOGIN >= 90 AND NOT IS_DISABLED THEN USER_NAME END
  ) AS "SEC_DORMANT_USERS",
  COUNT(DISTINCT CASE WHEN NOT HAS_RSA_PUBLIC_KEY AND NOT IS_DISABLED THEN USER_NAME END) AS "SEC_USERS_WITHOUT_KEY_PAIR"
FROM (
  SELECT
    "USER_ID" AS USER_ID,
    "NAME" AS USER_NAME,
    "LOGIN_NAME" AS LOGIN_NAME,
    "DEFAULT_ROLE" AS DEFAULT_ROLE,
    "DEFAULT_WAREHOUSE" AS DEFAULT_WAREHOUSE,
    "TYPE" AS USER_TYPE,
    COALESCE("DISABLED", FALSE) AS IS_DISABLED,
    COALESCE("HAS_PASSWORD", FALSE) AS HAS_PASSWORD,
    COALESCE("HAS_RSA_PUBLIC_KEY", FALSE) AS HAS_RSA_PUBLIC_KEY,
    (
      TRY_TO_TIMESTAMP_NTZ("LAST_SUCCESS_LOGIN")
    ) AS LAST_SUCCESS_LOGIN_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("CREATED_ON")
    ) AS CREATED_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("DELETED_ON")
    ) AS DELETED_AT,
    MAX((
      TRY_TO_TIMESTAMP_NTZ("LAST_SUCCESS_LOGIN")
    )) OVER () AS SNAPSHOT_AT,
    (
      CAST(CASE
        WHEN (
          86400
        ) = 0 OR (
          86400
        ) IS NULL
        THEN NULL
        ELSE CAST((
          (
            DATEDIFF(
              SECOND,
              (
                TRY_TO_TIMESTAMP_NTZ("LAST_SUCCESS_LOGIN")
              ),
              MAX((
                TRY_TO_TIMESTAMP_NTZ("LAST_SUCCESS_LOGIN")
              )) OVER ()
            )
          )
        ) AS DECIMAL(38, 15)) / CAST((
          86400
        ) AS DECIMAL(38, 15))
      END AS DECIMAL(38, 15))
    ) AS DAYS_SINCE_LAST_LOGIN
  FROM users
) AS base
GROUP BY
  USER_NAME,
  COALESCE(USER_TYPE, 'UNKNOWN'),
  COALESCE(DEFAULT_ROLE, 'NONE'),
  CASE WHEN IS_DISABLED THEN 'DISABLED' ELSE 'ACTIVE' END,
  CASE
    WHEN HAS_RSA_PUBLIC_KEY AND HAS_PASSWORD
    THEN 'KEY_AND_PASSWORD'
    WHEN HAS_RSA_PUBLIC_KEY
    THEN 'KEY_PAIR'
    WHEN HAS_PASSWORD
    THEN 'PASSWORD_ONLY'
    ELSE 'FEDERATED_OR_NONE'
  END;
