-- Security & Access Governance 1.0.0 — semantic view
--
-- Cortex Analyst reads this view to answer questions about the product.
-- 18 verified queries teach it the team's vocabulary.
--
-- Additive measures are METRICS; ratios, percentiles, and distinct counts
-- are FACTS, because re-aggregating them would produce a wrong number.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE SEMANTIC VIEW OBSERVABILITY.SEMANTIC.ACCESS_GOVERNANCE
  TABLES (
    access_governance_login AS OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
      PRIMARY KEY (TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP)
      COMMENT = 'Security & Access Governance: Login attempt.',
    access_governance_grant AS OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
      PRIMARY KEY (TIME_BUCKET, ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER)
      COMMENT = 'Security & Access Governance: Role grant to user.',
    access_governance_user AS OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER
      PRIMARY KEY (USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE)
      COMMENT = 'Security & Access Governance: User.'
  )
  FACTS (
    access_governance_login.SEC_FAILED_LOGIN_RATE AS SEC_FAILED_LOGIN_RATE
      WITH SYNONYMS = ('authentication failures', 'failed auth rate', 'failed login rate', 'login failure rate')
      COMMENT = 'Share of authentication attempts that failed. A background rate of a few percent is normal — mistyped passwords, expired sessions. A step change on one user or one client type is not, and that is what the slice is for. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    access_governance_login.SEC_DISTINCT_CLIENT_IPS AS SEC_DISTINCT_CLIENT_IPS
      WITH SYNONYMS = ('connection origins', 'distinct client ips per user', 'impossible travel', 'ip spread', 'source addresses')
      COMMENT = 'Number of distinct source addresses a user authenticated from. A service account pinned to a network allowlist should be a small constant; a jump is either an infrastructure change nobody mentioned or a credential in the wrong hands. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    access_governance_grant.SEC_DISABLED_BUT_GRANTED_USERS AS SEC_DISABLED_BUT_GRANTED_USERS
      WITH SYNONYMS = ('deprovisioning gap', 'disabled but granted', 'disabled users still holding roles', 'orphaned grants')
      COMMENT = 'Disabled accounts that still hold live role grants. Disabling a user stops them logging in but leaves the grant graph untouched, so this is the deprovisioning tail: the difference between "cannot sign in today" and "has no access", which is the difference that matters if the account is ever re-enabled. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    access_governance_user.SEC_DORMANT_USERS AS SEC_DORMANT_USERS
      WITH SYNONYMS = ('dormant accounts', 'dormant users', 'inactive users', 'stale users', 'unused accounts')
      COMMENT = 'Enabled users with no successful login in 90 days. Every one is a live credential with no owner watching it — the cheapest access risk to remove and the one most often left alone because nobody is sure who it belongs to. Age is measured against the newest login in the snapshot, so the cohort is stable between runs. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    access_governance_user.SEC_USERS_WITHOUT_KEY_PAIR AS SEC_USERS_WITHOUT_KEY_PAIR
      WITH SYNONYMS = ('key pair rollout', 'no key pair', 'password auth', 'rsa key gap', 'users without an rsa key')
      COMMENT = 'Enabled users with no RSA public key configured. Sliced by user_type this is the key-pair rollout backlog for service accounts, which cannot use interactive MFA and must move to key-pair authentication before password sign-in is blocked. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.'
  )
  DIMENSIONS (
    access_governance_login.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over EVENT_AT, at the coarsest grain the product''s metrics declare.',
    access_governance_login.USER AS USER
      WITH SYNONYMS = ('user')
      COMMENT = 'User the attempt was made against.',
    access_governance_login.CLIENT_TYPE AS CLIENT_TYPE
      WITH SYNONYMS = ('client type')
      COMMENT = 'Reported driver or client (JDBC, PYTHON_DRIVER, SNOWFLAKE_UI, …).',
    access_governance_login.FIRST_FACTOR AS FIRST_FACTOR
      WITH SYNONYMS = ('first factor')
      COMMENT = 'First authentication factor (PASSWORD, RSA_KEYPAIR, OAUTH, …).',
    access_governance_login.ERROR_CLASS AS ERROR_CLASS
      WITH SYNONYMS = ('error class')
      COMMENT = 'Snowflake error code of a failed attempt, or NONE.',
    access_governance_login.CLIENT_IP AS CLIENT_IP
      WITH SYNONYMS = ('client ip')
      COMMENT = 'Source IP of the attempt.',
    access_governance_grant.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over GRANTED_AT, at the coarsest grain the product''s metrics declare.',
    access_governance_grant.ROLE AS ROLE
      WITH SYNONYMS = ('role')
      COMMENT = 'Role granted.',
    access_governance_grant.GRANTEE AS GRANTEE
      WITH SYNONYMS = ('grantee')
      COMMENT = 'User the role was granted to.',
    access_governance_grant.GRANTED_BY AS GRANTED_BY
      WITH SYNONYMS = ('granted by')
      COMMENT = 'Role that issued the grant.',
    access_governance_grant.GRANTEE_TYPE AS GRANTEE_TYPE
      WITH SYNONYMS = ('grantee type')
      COMMENT = 'PERSON, SERVICE, or LEGACY_SERVICE.',
    access_governance_grant.PRIVILEGE_TIER AS PRIVILEGE_TIER
      WITH SYNONYMS = ('privilege tier')
      COMMENT = 'PRIVILEGED for the account-administration roles, STANDARD otherwise.',
    access_governance_user.USER AS USER
      WITH SYNONYMS = ('user')
      COMMENT = 'User name.',
    access_governance_user.USER_TYPE AS USER_TYPE
      WITH SYNONYMS = ('user type')
      COMMENT = 'PERSON, SERVICE, or LEGACY_SERVICE.',
    access_governance_user.DEFAULT_ROLE AS DEFAULT_ROLE
      WITH SYNONYMS = ('default role')
      COMMENT = 'Role the user assumes on connect when none is specified.',
    access_governance_user.ACCOUNT_STATUS AS ACCOUNT_STATUS
      WITH SYNONYMS = ('account status')
      COMMENT = 'Whether the user is currently disabled.',
    access_governance_user.CREDENTIAL_TYPE AS CREDENTIAL_TYPE
      WITH SYNONYMS = ('credential type')
      COMMENT = 'Credentials configured on the user — the key-pair rollout view.'
  )
  METRICS (
    access_governance_login.SEC_FAILED_LOGINS AS SUM(SEC_FAILED_LOGINS)
      WITH SYNONYMS = ('bad password attempts', 'brute force', 'failed logins', 'failed logins per user')
      COMMENT = 'Count of failed authentication attempts. Per user and per source IP this is the shape a credential-stuffing attempt makes: many failures against many users from few addresses, or many failures against one user from many.',
    access_governance_login.SEC_SINGLE_FACTOR_LOGINS AS SUM(SEC_SINGLE_FACTOR_LOGINS)
      WITH SYNONYMS = ('mfa gap', 'no mfa', 'password only logins', 'single factor', 'single-factor logins')
      COMMENT = 'Successful logins that presented no second authentication factor. Snowflake blocks single-factor password sign-in from October 2026, so this is a migration burn-down: every login counted here is one that will stop working. Key-pair service authentication legitimately has no second factor and shows up here too — slice by first_factor to separate the two populations.',
    access_governance_grant.SEC_PRIVILEGED_GRANTS AS SUM(SEC_PRIVILEGED_GRANTS)
      WITH SYNONYMS = ('accountadmin', 'accountadmin-adjacent grants', 'admin roles', 'privileged access', 'super users')
      COMMENT = 'Live grants of ACCOUNTADMIN, SECURITYADMIN, or ORGADMIN. These roles can change billing, read every object, and rewrite the access model, so the right number is small, known, and unchanging — and any movement in it should be traceable to a ticket. Revoked grants are excluded so the figure is current holdings rather than everything ever granted.',
    access_governance_grant.SEC_NEW_GRANTS AS SUM(SEC_NEW_GRANTS)
      WITH SYNONYMS = ('access changes', 'grants issued', 'new access', 'new grants in window', 'privilege drift')
      COMMENT = 'Grants created inside the requested window, from GRANTS_TO_USERS.CREATED_ON. This is the privilege-drift feed: a review reads it in date order and asks who approved each row. Sliced by privilege_tier it separates routine team membership from a new administrator.'
  )
  COMMENT = 'Authentication and privilege posture: failed logins and their error classes, single-factor authentication still in use ahead of the October 2026 MFA cut-off, client-IP spread per user, privileged and newly granted roles, and identities that are dormant or hold grants while disabled. Restricted: the product carries per-user activity and is masked and row-secured on publication.'
  AI_VERIFIED_QUERIES (
    vq_sec_failed_logins_1 AS (
      QUESTION 'users with the most failed logins'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_FAILED_LOGINS) AS SEC_FAILED_LOGINS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP
ORDER BY SEC_FAILED_LOGINS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_failed_logins_2 AS (
      QUESTION 'failed logins by IP'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_FAILED_LOGINS) AS SEC_FAILED_LOGINS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP
ORDER BY SEC_FAILED_LOGINS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_failed_login_rate_1 AS (
      QUESTION 'failed login rate this week'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_FAILED_LOGIN_RATE
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_FAILED_LOGIN_RATE DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_failed_login_rate_2 AS (
      QUESTION 'login failures by client'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_FAILED_LOGIN_RATE
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_FAILED_LOGIN_RATE DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_single_factor_logins_1 AS (
      QUESTION 'who still logs in without MFA'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_SINGLE_FACTOR_LOGINS) AS SEC_SINGLE_FACTOR_LOGINS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP
ORDER BY SEC_SINGLE_FACTOR_LOGINS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_single_factor_logins_2 AS (
      QUESTION 'single factor logins by user'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_SINGLE_FACTOR_LOGINS) AS SEC_SINGLE_FACTOR_LOGINS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP
ORDER BY SEC_SINGLE_FACTOR_LOGINS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_distinct_client_ips_1 AS (
      QUESTION 'users logging in from many IPs'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_DISTINCT_CLIENT_IPS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_DISTINCT_CLIENT_IPS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_distinct_client_ips_2 AS (
      QUESTION 'IP spread for SVC accounts'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_DISTINCT_CLIENT_IPS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_DISTINCT_CLIENT_IPS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_privileged_grants_1 AS (
      QUESTION 'who has ACCOUNTADMIN'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SUM(SEC_PRIVILEGED_GRANTS) AS SEC_PRIVILEGED_GRANTS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER
ORDER BY SEC_PRIVILEGED_GRANTS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_privileged_grants_2 AS (
      QUESTION 'privileged role grants'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SUM(SEC_PRIVILEGED_GRANTS) AS SEC_PRIVILEGED_GRANTS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER
ORDER BY SEC_PRIVILEGED_GRANTS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_new_grants_1 AS (
      QUESTION 'new grants this week'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SUM(SEC_NEW_GRANTS) AS SEC_NEW_GRANTS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER
ORDER BY SEC_NEW_GRANTS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_new_grants_2 AS (
      QUESTION 'privileged grants issued recently'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SUM(SEC_NEW_GRANTS) AS SEC_NEW_GRANTS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER
ORDER BY SEC_NEW_GRANTS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_disabled_but_granted_users_1 AS (
      QUESTION 'disabled users who still have roles'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SEC_DISABLED_BUT_GRANTED_USERS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_DISABLED_BUT_GRANTED_USERS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_disabled_but_granted_users_2 AS (
      QUESTION 'deprovisioning gaps'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, SEC_DISABLED_BUT_GRANTED_USERS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SEC_DISABLED_BUT_GRANTED_USERS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_dormant_users_1 AS (
      QUESTION 'dormant users'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE, SEC_DORMANT_USERS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER
ORDER BY SEC_DORMANT_USERS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_dormant_users_2 AS (
      QUESTION 'accounts with no login in 90 days'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE, SEC_DORMANT_USERS
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER
ORDER BY SEC_DORMANT_USERS DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_users_without_key_pair_1 AS (
      QUESTION 'service accounts without a key pair'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE, SEC_USERS_WITHOUT_KEY_PAIR
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER
ORDER BY SEC_USERS_WITHOUT_KEY_PAIR DESC NULLS LAST
LIMIT 20'
    ),
    vq_sec_users_without_key_pair_2 AS (
      QUESTION 'key pair rollout progress'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = security-engineering@internal)'
      SQL 'SELECT USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS, CREDENTIAL_TYPE, SEC_USERS_WITHOUT_KEY_PAIR
FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER
ORDER BY SEC_USERS_WITHOUT_KEY_PAIR DESC NULLS LAST
LIMIT 20'
    )
  )
;
