-- Security & Access Governance 1.0.0 — share and organization listing
--
-- Publishes the product to the organization's internal marketplace.
--
-- The share carries the PUBLISHED and SEMANTIC schemas only — never the
-- curated or raw layers — and grants each object by name.
--
-- PUBLISH = FALSE: the listing is created but not offered. Publishing it
-- to the organization is a separate, deliberate act by a human (R8).
--
-- Requires ORGADMIN (or an organization account) to create an
-- organization listing.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE ACCOUNTADMIN;

CREATE SHARE IF NOT EXISTS SHARE_ACCESS_GOVERNANCE
  COMMENT = 'Security & Access Governance 1.0.0 — internal share';

GRANT USAGE ON DATABASE OBSERVABILITY TO SHARE SHARE_ACCESS_GOVERNANCE;
GRANT USAGE ON SCHEMA OBSERVABILITY.PUBLISHED TO SHARE SHARE_ACCESS_GOVERNANCE;
GRANT USAGE ON SCHEMA OBSERVABILITY.SEMANTIC TO SHARE SHARE_ACCESS_GOVERNANCE;

GRANT SELECT ON VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN TO SHARE SHARE_ACCESS_GOVERNANCE;
GRANT SELECT ON VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_GRANT TO SHARE SHARE_ACCESS_GOVERNANCE;
GRANT SELECT ON VIEW OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_USER TO SHARE SHARE_ACCESS_GOVERNANCE;

GRANT REFERENCES ON SEMANTIC VIEW OBSERVABILITY.SEMANTIC.ACCESS_GOVERNANCE TO SHARE SHARE_ACCESS_GOVERNANCE;

CREATE ORGANIZATION LISTING IF NOT EXISTS LST_ACCESS_GOVERNANCE
  SHARE SHARE_ACCESS_GOVERNANCE
  AS $$
title: Security & Access Governance
subtitle: 'Authentication and privilege posture: failed logins and their error classes, single-factor
  authentication stil'
description: "Authentication and privilege posture: failed logins and their error classes, single-factor\
  \ authentication still in use ahead of the October 2026 MFA cut-off, client-IP spread per user, privileged\
  \ and newly granted roles, and identities that are dormant or hold grants while disabled. Restricted:\
  \ the product carries per-user activity and is masked and row-secured on publication.\n\nOwner: security-engineering\
  \ · support: security-engineering@internal\nClassification: restricted\nFreshness guarantee: 2 h (the\
  \ documented latency of the slowest source behind this product).\nAvailability target: 99.9% · retention:\
  \ 365 days\nDeprecation notice: 90 days\n\nRelations (3):\n  - V_ACCESS_GOVERNANCE_LOGIN — 10 columns,\
  \ grain TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, freshness 2 h\n  - V_ACCESS_GOVERNANCE_GRANT\
  \ — 9 columns, grain TIME_BUCKET, ROLE, GRANTEE, GRANTED_BY, GRANTEE_TYPE, PRIVILEGE_TIER, freshness\
  \ 2 h\n  - V_ACCESS_GOVERNANCE_USER — 7 columns, grain USER, USER_TYPE, DEFAULT_ROLE, ACCOUNT_STATUS,\
  \ CREDENTIAL_TYPE, freshness 2 h\n\nGoverned metrics (9): sec.disabled_but_granted_users, sec.distinct_client_ips,\
  \ sec.dormant_users, sec.failed_login_rate, sec.failed_logins, sec.new_grants, sec.privileged_grants,\
  \ sec.single_factor_logins, sec.users_without_key_pair\n\nBreaking-change policy: Removing a column,\
  \ changing its type, relaxing its nullability, rebinding it to a different governed metric, changing\
  \ the grain, loosening the freshness guarantee, or shortening retention is a BREAKING change: it requires\
  \ a major version, a migration note, and the full deprecation notice period. Everything else is additive\
  \ and ships as a minor or patch version."
organization_profile: INTERNAL
organization_targets:
  access:
  - all_accounts: true
  support_contact: security-engineering@internal
  approver_contact: security-engineering@internal
auto_fulfillment:
  refresh_schedule: 4 HOUR
  refresh_type: SUB_DATABASE
categories:
- SECURITY
- IT_OPERATIONS
resources:
  documentation: https://internal.docs/data-products/access-governance
  support: security-engineering@internal
data_dictionary:
  featured:
  - database_name: OBSERVABILITY
    objects:
    - name: V_ACCESS_GOVERNANCE_LOGIN
      schema: PUBLISHED
      domain: VIEW
    - name: V_ACCESS_GOVERNANCE_GRANT
      schema: PUBLISHED
      domain: VIEW
    - name: V_ACCESS_GOVERNANCE_USER
      schema: PUBLISHED
      domain: VIEW
    - name: ACCESS_GOVERNANCE
      schema: SEMANTIC
      domain: SEMANTIC_VIEW
usage_examples:
- title: users with the most failed logins
  description: Answered from the product's own published views; the same SQL is a verified query on the
    ACCESS_GOVERNANCE semantic view.
  query: 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_FAILED_LOGINS) AS SEC_FAILED_LOGINS

    FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP

    ORDER BY SEC_FAILED_LOGINS DESC NULLS LAST

    LIMIT 20;'
- title: failed logins by IP
  description: Answered from the product's own published views; the same SQL is a verified query on the
    ACCESS_GOVERNANCE semantic view.
  query: 'SELECT USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SUM(SEC_FAILED_LOGINS) AS SEC_FAILED_LOGINS

    FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    GROUP BY USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP

    ORDER BY SEC_FAILED_LOGINS DESC NULLS LAST

    LIMIT 20;'
- title: failed login rate this week
  description: Answered from the product's own published views; the same SQL is a verified query on the
    ACCESS_GOVERNANCE semantic view.
  query: 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_FAILED_LOGIN_RATE

    FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    ORDER BY SEC_FAILED_LOGIN_RATE DESC NULLS LAST

    LIMIT 20;'
- title: login failures by client
  description: Answered from the product's own published views; the same SQL is a verified query on the
    ACCESS_GOVERNANCE semantic view.
  query: 'SELECT TIME_BUCKET, USER, CLIENT_TYPE, FIRST_FACTOR, ERROR_CLASS, CLIENT_IP, SEC_FAILED_LOGIN_RATE

    FROM OBSERVABILITY.PUBLISHED.V_ACCESS_GOVERNANCE_LOGIN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    ORDER BY SEC_FAILED_LOGIN_RATE DESC NULLS LAST

    LIMIT 20;'
$$
  PUBLISH = FALSE;

SHOW ORGANIZATION LISTINGS LIKE 'LST_ACCESS_GOVERNANCE';
