-- V_FINOPS_CHARGEBACK_QUERY_EXECUTION · Platform Cost & Attribution 1.1.0
-- Generated from the governed metrics chargeback.allocated_credits, cost.by_team_credits, chargeback.unattributed_credits, chargeback.unattributed_share.
-- Edit the metric YAML, not this file: it is regenerated on every publish.
{{ config(materialized='table', on_schema_change='append_new_columns') }}

WITH product AS (
  SELECT
    (
      DATE_TRUNC('DAY', "STARTED_AT")
    ) AS "TIME_BUCKET",
    COALESCE(QUERY_TAG_TEAM, 'UNATTRIBUTED') AS "TEAM",
    WAREHOUSE_NAME AS "WAREHOUSE",
    DATABASE_NAME AS "DATABASE",
    CASE WHEN QUERY_TAG_TEAM IS NULL THEN 'RESIDUAL_POOL' ELSE 'DIRECT_TAG' END AS "ALLOCATION_METHOD",
    SUM(CREDITS_ATTRIBUTED) AS "CHARGEBACK_ALLOCATED_CREDITS",
    SUM(CREDITS_ATTRIBUTED) AS "COST_BY_TEAM_CREDITS",
    SUM(CASE WHEN QUERY_TAG_TEAM IS NULL THEN CREDITS_ATTRIBUTED ELSE 0 END) AS "CHARGEBACK_UNATTRIBUTED_CREDITS",
    (
      CAST(CASE
        WHEN (
          SUM(CREDITS_ATTRIBUTED)
        ) = 0 OR (
          SUM(CREDITS_ATTRIBUTED)
        ) IS NULL
        THEN NULL
        ELSE CAST((
          SUM(CASE WHEN QUERY_TAG_TEAM IS NULL THEN CREDITS_ATTRIBUTED ELSE 0 END)
        ) AS DECIMAL(38, 15)) / CAST((
          SUM(CREDITS_ATTRIBUTED)
        ) AS DECIMAL(38, 15))
      END AS DECIMAL(38, 15))
    ) AS "CHARGEBACK_UNATTRIBUTED_SHARE"
  FROM (
    SELECT
      q."QUERY_ID" AS QUERY_ID,
      (
        TRY_TO_TIMESTAMP_NTZ(q."START_TIME")
      ) AS STARTED_AT,
      q."WAREHOUSE_NAME" AS WAREHOUSE_NAME,
      q."WAREHOUSE_SIZE" AS WAREHOUSE_SIZE,
      q."USER_NAME" AS USER_NAME,
      q."ROLE_NAME" AS ROLE_NAME,
      q."DATABASE_NAME" AS DATABASE_NAME,
      q."QUERY_TYPE" AS QUERY_TYPE,
      q."EXECUTION_STATUS" AS EXECUTION_STATUS,
      q."ERROR_CODE" AS ERROR_CODE,
      q."QUERY_PARAMETERIZED_HASH" AS FINGERPRINT,
      (
        JSON_EXTRACT_PATH_TEXT(q."QUERY_TAG", 'team')
      ) AS QUERY_TAG_TEAM,
      q."TOTAL_ELAPSED_TIME" AS ELAPSED_MS,
      q."COMPILATION_TIME" AS COMPILATION_MS,
      q."EXECUTION_TIME" AS EXECUTION_MS,
      q."QUEUED_OVERLOAD_TIME" AS QUEUED_OVERLOAD_MS,
      q."QUEUED_PROVISIONING_TIME" AS QUEUED_PROVISIONING_MS,
      q."BYTES_SCANNED" AS BYTES_SCANNED,
      q."BYTES_SPILLED_TO_LOCAL_STORAGE" AS BYTES_SPILLED_LOCAL,
      q."BYTES_SPILLED_TO_REMOTE_STORAGE" AS BYTES_SPILLED_REMOTE,
      q."PARTITIONS_SCANNED" AS PARTITIONS_SCANNED,
      q."PARTITIONS_TOTAL" AS PARTITIONS_TOTAL,
      q."PERCENTAGE_SCANNED_FROM_CACHE" AS CACHE_FRACTION,
      (
        CAST(COALESCE(a."CREDITS_ATTRIBUTED_COMPUTE", 0) AS DECIMAL(38, 9))
      ) AS CREDITS_ATTRIBUTED,
      (
        TRY_TO_TIMESTAMP_NTZ(q."_LOADED_AT")
      ) AS LANDED_AT, /* Landing time: its gap from STARTED_AT is this platform's own freshness. */
      (
        NULL
      ) AS ACCOUNT_NAME /* Which account these rows came from. A stamped column OFFLINE, where one */ /* lake holds several accounts; the connection LIVE, where it is not in the */ /* data at all (see the ACCOUNT_OF shim). */
    FROM {{ source('account_usage', 'QUERY_HISTORY') }} AS q
    LEFT JOIN {{ source('account_usage', 'QUERY_ATTRIBUTION_HISTORY') }} AS a
      ON a."QUERY_ID" = q."QUERY_ID"
  ) AS base
  GROUP BY
    (
      DATE_TRUNC('DAY', "STARTED_AT")
    ),
    COALESCE(QUERY_TAG_TEAM, 'UNATTRIBUTED'),
    WAREHOUSE_NAME,
    DATABASE_NAME,
    CASE WHEN QUERY_TAG_TEAM IS NULL THEN 'RESIDUAL_POOL' ELSE 'DIRECT_TAG' END
)
SELECT
  product.*,
  CURRENT_TIMESTAMP() AS _LOADED_AT,
  'V_FINOPS_CHARGEBACK_QUERY_EXECUTION' AS _SOURCE_VIEW,
  '{{ invocation_id }}' AS _BATCH_ID
FROM product
