# Stateful services: Postgres for app metadata, Redis for the queue and shared
# cache, S3 for the data lake.
#
# What lives where matters here (R2). Postgres holds users, products, contracts,
# approvals, and the audit log — application metadata. It does not hold
# telemetry: raw ACCOUNT_USAGE rows stay in Snowflake in LIVE mode, and in the
# S3 lake as Parquet in OFFLINE mode. Sizing the database as if it were a
# warehouse is the most common way to overspend on this platform.
#
# The master password is managed by RDS in Secrets Manager
# (manage_master_user_password), so it is never generated by Terraform and never
# appears in state (§27.13). That is the whole reason this module does not take
# a password variable.

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-db"
  subnet_ids = var.private_subnet_ids
  tags       = var.tags
}

resource "aws_db_parameter_group" "this" {
  name   = "${var.name}-pg16"
  family = "postgres16"

  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  # Refuse unencrypted connections. The application connects with
  # postgresql+asyncpg over TLS; anything that cannot is misconfigured.
  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name}-postgres"
  engine         = "postgres"
  engine_version = var.postgres_version
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage_gb
  max_allocated_storage = var.db_max_allocated_storage_gb
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_arn

  db_name  = "snowobs"
  username = "snowobs"
  # RDS creates and rotates the master password in Secrets Manager. No password
  # is passed in, so none is stored in state.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = var.kms_key_arn

  db_subnet_group_name   = aws_db_subnet_group.this.name
  parameter_group_name   = aws_db_parameter_group.this.name
  vpc_security_group_ids = [var.database_security_group_id]
  publicly_accessible    = false
  multi_az               = var.db_multi_az

  backup_retention_period = var.backup_retention_days
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true
  deletion_protection     = var.deletion_protection
  # Named final snapshot unless the environment explicitly opts out, so a
  # `terraform destroy` in the wrong directory is survivable.
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  auto_minor_version_upgrade      = true
  performance_insights_enabled    = var.performance_insights_enabled
  performance_insights_kms_key_id = var.performance_insights_enabled ? var.kms_key_arn : null
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  apply_immediately = var.apply_immediately

  lifecycle {
    # The snapshot identifier embeds a timestamp, which would otherwise show as
    # a diff on every plan.
    ignore_changes = [final_snapshot_identifier]
  }

  tags = var.tags
}

# ── Redis: arq's queue, and the shared result cache ─────────────────────────
resource "aws_elasticache_subnet_group" "this" {
  name       = "${var.name}-cache"
  subnet_ids = var.private_subnet_ids
  tags       = var.tags
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id = "${var.name}-redis"
  description          = "${var.name} — arq queue and result cache"

  engine         = "redis"
  engine_version = var.redis_version
  node_type      = var.redis_node_type
  port           = 6379

  num_cache_clusters         = var.redis_replica_count + 1
  automatic_failover_enabled = var.redis_replica_count > 0
  multi_az_enabled           = var.redis_replica_count > 0

  subnet_group_name  = aws_elasticache_subnet_group.this.name
  security_group_ids = [var.cache_security_group_id]

  at_rest_encryption_enabled = true
  kms_key_id                 = var.kms_key_arn
  # In-transit encryption without an auth token: the token would be a secret
  # value in state (§27.13), and the cache is reachable only from the
  # application security group. TLS still protects the wire.
  transit_encryption_enabled = true

  maintenance_window       = var.maintenance_window
  snapshot_retention_limit = var.redis_snapshot_retention_days
  apply_immediately        = var.apply_immediately

  tags = var.tags
}

# ── S3: uploads, landed Parquet, exports ────────────────────────────────────
resource "aws_s3_bucket" "lake" {
  bucket = var.data_lake_bucket_name
  tags   = var.tags
}

resource "aws_s3_bucket_public_access_block" "lake" {
  bucket = aws_s3_bucket.lake.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "lake" {
  bucket = aws_s3_bucket.lake.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_versioning" "lake" {
  bucket = aws_s3_bucket.lake.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "lake" {
  bucket = aws_s3_bucket.lake.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = var.kms_key_arn
    }
    # One data key per request would be a per-object KMS call on a lake with
    # millions of Parquet parts; the bucket key collapses that.
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "lake" {
  bucket = aws_s3_bucket.lake.id

  rule {
    id     = "uploads-ttl"
    status = "Enabled"

    filter {
      prefix = "uploads/"
    }

    # §17: uploaded extracts are purged on a configurable TTL. They are the
    # customer's telemetry and there is no reason to keep them once landed.
    expiration {
      days = var.upload_retention_days
    }

    noncurrent_version_expiration {
      noncurrent_days = 7
    }
  }

  rule {
    id     = "curated-tiering"
    status = "Enabled"

    filter {
      prefix = "curated/"
    }

    transition {
      days          = 90
      storage_class = "STANDARD_IA"
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }

  rule {
    id     = "abort-incomplete-uploads"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

# Deny anything that is not TLS. Cheap, and it closes the "someone used the
# HTTP endpoint from inside the VPC" hole that audits always ask about.
resource "aws_s3_bucket_policy" "lake" {
  bucket = aws_s3_bucket.lake.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "DenyInsecureTransport"
      Effect    = "Deny"
      Principal = "*"
      Action    = "s3:*"
      Resource = [
        aws_s3_bucket.lake.arn,
        "${aws_s3_bucket.lake.arn}/*",
      ]
      Condition = {
        Bool = { "aws:SecureTransport" = "false" }
      }
    }]
  })
}
