-- Pipeline Reliability 1.0.0 — Cortex Search service
--
-- Indexes TASK from V_PIPELINE_HEALTH_TASK_RUN over a 30-day window.
--
-- Only columns the contract marks searchable are indexed. Sensitive
-- columns and query text are never indexed (R2, §12.5).
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).
USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE CORTEX SEARCH SERVICE OBSERVABILITY.SEARCH.PIPELINE_HEALTH_TASK
  ON TASK
  ATTRIBUTES DATABASE, TASK_SCHEMA, GRAPH_ROOT, ERROR_CLASS
  WAREHOUSE = WH_SNOWOBS_APP
  TARGET_LAG = '1 hour'
  COMMENT = 'Free-text search over TASK in V_PIPELINE_HEALTH_TASK_RUN for Pipeline Reliability 1.0.0. Indexed window: 30 days.'
  AS (
    SELECT TASK, DATABASE, TASK_SCHEMA, GRAPH_ROOT, ERROR_CLASS
      FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
      WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
        AND TASK IS NOT NULL
  );
