-- Pipeline Reliability 1.0.0 — published views
--
-- Product: pipeline_health · owner: data-engineering · classification: internal
-- Freshness guarantee: 180 minutes (the slowest source behind this product).
--
-- Each view is the semantic layer's own compiled SQL for the metrics in
-- the product's boundary — the same query a dashboard tile runs, so a
-- consumer and a tile can never disagree about a figure (R1, R5).
--
-- The interactive row cap the SQL guard forces on ad-hoc execution is
-- deliberately absent here: a published relation is not truncated.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;
USE WAREHOUSE WH_SNOWOBS_APP;

-- V_PIPELINE_HEALTH_TASK_RUN: 11 columns · sources task_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN (
  TIME_BUCKET COMMENT 'Time bucket over SCHEDULED_AT, at the coarsest grain the product''s metrics declare.',
  TASK COMMENT 'Task name.',
  GRAPH_ROOT COMMENT 'Root task of the DAG the run belongs to — the roll-up key.',
  ERROR_CLASS COMMENT 'Snowflake error code of the run, or NONE when it succeeded.',
  DATABASE COMMENT 'Database the task is defined in.',
  TASK_SCHEMA COMMENT 'Schema the task is defined in.',
  PIPE_TASK_SUCCESS_RATE COMMENT 'Share of task runs that completed successfully. SKIPPED runs are in the denominator on purpose: a graph that is repeatedly suspended is not delivering data, however healthy its individual statements look.',
  PIPE_TASK_FAILURES COMMENT 'Count of task runs that ended in FAILED. Sliced by error class this separates the timeouts from the genuinely broken SQL, which want different responses.',
  PIPE_ROOT_FAILURES COMMENT 'Failures at the root of a task graph — the incidents worth paging on. A root failure suspends everything beneath it, so this count is what an alert should carry while the downstream SKIPPED runs stay context rather than separate notifications.',
  PIPE_SKIPPED_DOWNSTREAM COMMENT 'Runs skipped because something upstream failed. Read against pipe.root_failures this is the blast radius of an incident: one root failure, twelve tables that did not refresh.',
  PIPE_TASK_DURATION_P95 COMMENT '95th-percentile wall-clock duration from scheduled time to completion, per task. Measured from *scheduled* rather than started time deliberately: a task that waits ten minutes for a warehouse has been late by ten minutes, whatever its statement timing says. The percentile is taken from a nearest-rank window computed over the task''s retained history rather than through the PERCENTILE shim, because Snowflake estimates percentiles from a t-digest and DuckDB computes them exactly — a difference no task-duration tail has enough observations to absorb. Unit: seconds.'
)
  COMMENT = 'Pipeline Reliability: Task run. Grain: TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA. Freshness floor 45 minutes. Product pipeline_health 1.0.0, owner data-engineering.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "SCHEDULED_AT")
  ) AS "TIME_BUCKET",
  TASK_NAME AS "TASK",
  COALESCE(GRAPH_ROOT_TASK_ID, TASK_NAME) AS "GRAPH_ROOT",
  COALESCE(ERROR_CODE, 'NONE') AS "ERROR_CLASS",
  DATABASE_NAME AS "DATABASE",
  SCHEMA_NAME AS "TASK_SCHEMA",
  (
    CAST(CASE
      WHEN (
        COUNT(*)
      ) = 0 OR (
        COUNT(*)
      ) IS NULL
      THEN NULL
      ELSE CAST((
        SUM(CASE WHEN STATE = 'SUCCEEDED' THEN 1 ELSE 0 END)
      ) AS DECIMAL(38, 15)) / CAST((
        COUNT(*)
      ) AS DECIMAL(38, 15))
    END AS DECIMAL(38, 15))
  ) AS "PIPE_TASK_SUCCESS_RATE",
  SUM(CASE WHEN STATE = 'FAILED' THEN 1 ELSE 0 END) AS "PIPE_TASK_FAILURES",
  SUM(CASE WHEN STATE = 'FAILED' AND TASK_NAME = GRAPH_ROOT_TASK_ID THEN 1 ELSE 0 END) AS "PIPE_ROOT_FAILURES",
  SUM(CASE WHEN STATE = 'SKIPPED' THEN 1 ELSE 0 END) AS "PIPE_SKIPPED_DOWNSTREAM",
  MAX(CASE WHEN DURATION_PERCENT_RANK <= 0.95 THEN DURATION_SEC END) AS "PIPE_TASK_DURATION_P95"
FROM (
  SELECT
    "NAME" AS TASK_NAME,
    "DATABASE_NAME" AS DATABASE_NAME,
    "SCHEMA_NAME" AS SCHEMA_NAME,
    "STATE" AS STATE,
    "ERROR_CODE" AS ERROR_CODE,
    "QUERY_ID" AS QUERY_ID,
    "GRAPH_ROOT_TASK_ID" AS GRAPH_ROOT_TASK_ID,
    "GRAPH_RUN_GROUP_ID" AS GRAPH_RUN_GROUP_ID,
    "RUN_ID" AS RUN_ID,
    (
      TRY_TO_TIMESTAMP_NTZ("SCHEDULED_TIME")
    ) AS SCHEDULED_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("QUERY_START_TIME")
    ) AS STARTED_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("COMPLETED_TIME")
    ) AS COMPLETED_AT,
    (
      DATEDIFF(
        SECOND,
        (
          TRY_TO_TIMESTAMP_NTZ("SCHEDULED_TIME")
        ),
        (
          TRY_TO_TIMESTAMP_NTZ("COMPLETED_TIME")
        )
      )
    ) AS DURATION_SEC,
    PERCENT_RANK() OVER (
      PARTITION BY "NAME"
      ORDER BY (
        DATEDIFF(
          SECOND,
          (
            TRY_TO_TIMESTAMP_NTZ("SCHEDULED_TIME")
          ),
          (
            TRY_TO_TIMESTAMP_NTZ("COMPLETED_TIME")
          )
        )
      )
    ) AS DURATION_PERCENT_RANK,
    SUM(CASE WHEN "STATE" = 'FAILED' THEN 1 ELSE 0 END) OVER (PARTITION BY "NAME") AS TASK_FAILURE_COUNT,
    MAX(
      CASE
        WHEN "STATE" = 'SUCCEEDED'
        THEN (
          TRY_TO_TIMESTAMP_NTZ("COMPLETED_TIME")
        )
      END
    ) OVER (PARTITION BY "NAME") AS LAST_SUCCESS_AT,
    MAX((
      TRY_TO_TIMESTAMP_NTZ("SCHEDULED_TIME")
    )) OVER () AS OBSERVED_THROUGH_AT,
    (
      DATEDIFF(
        SECOND,
        MAX(
          CASE
            WHEN "STATE" = 'SUCCEEDED'
            THEN (
              TRY_TO_TIMESTAMP_NTZ("COMPLETED_TIME")
            )
          END
        ) OVER (PARTITION BY "NAME"),
        MAX((
          TRY_TO_TIMESTAMP_NTZ("SCHEDULED_TIME")
        )) OVER ()
      )
    ) AS SECONDS_SINCE_LAST_SUCCESS
  FROM task_history
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "SCHEDULED_AT")
  ),
  TASK_NAME,
  COALESCE(GRAPH_ROOT_TASK_ID, TASK_NAME),
  COALESCE(ERROR_CODE, 'NONE'),
  DATABASE_NAME,
  SCHEMA_NAME;

-- V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH: 10 columns · sources dynamic_table_refresh_history
CREATE OR REPLACE SECURE VIEW OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH (
  TIME_BUCKET COMMENT 'Time bucket over REFRESH_START_AT, at the coarsest grain the product''s metrics declare.',
  DYNAMIC_TABLE COMMENT 'Fully qualified dynamic table name.',
  DATABASE COMMENT 'Database the dynamic table lives in.',
  TABLE_SCHEMA COMMENT 'Schema the dynamic table lives in.',
  SLA_STATUS COMMENT 'Whether the refresh met its declared TARGET_LAG.',
  PIPE_DT_LAG_VS_TARGET COMMENT 'Actual lag as a fraction of declared TARGET_LAG. At or below 100% the table is meeting the freshness contract it advertises; above it, downstream consumers are reading data older than they were promised. Expressed as a ratio rather than raw seconds so tables with different targets are comparable on one axis.',
  PIPE_DT_LAG_BREACHES COMMENT 'Refreshes that started against data older than the table''s TARGET_LAG. Refreshes with no declared target are excluded rather than counted as passing — an unstated SLA is not a met one.',
  PIPE_DT_REFRESH_FAILURES COMMENT 'Refreshes that did not succeed, including UPSTREAM_FAILED — a dynamic table whose source failed is just as stale as one that failed itself, and the consumer cannot tell the difference.',
  DQ_FRESHNESS_SLA_ATTAINMENT COMMENT 'Share of dynamic-table refreshes that met the table''s own declared TARGET_LAG. Refreshes on tables with no target are excluded from both sides of the ratio rather than counted as successes — this measures attainment against stated SLAs, not the absence of one.',
  DQ_SLA_BREACH_COUNT COMMENT 'Number of refreshes that missed their declared target lag. Counted per refresh rather than per table so a table that breaches every hour is visibly worse than one that breached once.'
)
  COMMENT = 'Pipeline Reliability: Dynamic table refresh. Grain: TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS. Freshness floor 180 minutes. Product pipeline_health 1.0.0, owner data-engineering.'
AS
SELECT
  (
    DATE_TRUNC('DAY', "REFRESH_START_AT")
  ) AS "TIME_BUCKET",
  QUALIFIED_NAME AS "DYNAMIC_TABLE",
  DATABASE_NAME AS "DATABASE",
  SCHEMA_NAME AS "TABLE_SCHEMA",
  CASE
    WHEN TARGET_LAG_SEC IS NULL
    THEN 'NO_TARGET'
    WHEN ACTUAL_LAG_SEC > TARGET_LAG_SEC
    THEN 'BREACHED'
    ELSE 'WITHIN_TARGET'
  END AS "SLA_STATUS",
  (
    CAST(CASE
      WHEN (
        SUM(TARGET_LAG_SEC)
      ) = 0 OR (
        SUM(TARGET_LAG_SEC)
      ) IS NULL
      THEN NULL
      ELSE CAST((
        SUM(ACTUAL_LAG_SEC)
      ) AS DECIMAL(38, 15)) / CAST((
        SUM(TARGET_LAG_SEC)
      ) AS DECIMAL(38, 15))
    END AS DECIMAL(38, 15))
  ) AS "PIPE_DT_LAG_VS_TARGET",
  SUM(
    CASE
      WHEN NOT TARGET_LAG_SEC IS NULL AND ACTUAL_LAG_SEC > TARGET_LAG_SEC
      THEN 1
      ELSE 0
    END
  ) AS "PIPE_DT_LAG_BREACHES",
  SUM(CASE WHEN REFRESH_STATE <> 'SUCCEEDED' THEN 1 ELSE 0 END) AS "PIPE_DT_REFRESH_FAILURES",
  (
    CAST(CASE
      WHEN (
        SUM(CASE WHEN NOT TARGET_LAG_SEC IS NULL THEN 1 ELSE 0 END)
      ) = 0
      OR (
        SUM(CASE WHEN NOT TARGET_LAG_SEC IS NULL THEN 1 ELSE 0 END)
      ) IS NULL
      THEN NULL
      ELSE CAST((
        SUM(
          CASE
            WHEN NOT TARGET_LAG_SEC IS NULL AND ACTUAL_LAG_SEC <= TARGET_LAG_SEC
            THEN 1
            ELSE 0
          END
        )
      ) AS DECIMAL(38, 15)) / CAST((
        SUM(CASE WHEN NOT TARGET_LAG_SEC IS NULL THEN 1 ELSE 0 END)
      ) AS DECIMAL(38, 15))
    END AS DECIMAL(38, 15))
  ) AS "DQ_FRESHNESS_SLA_ATTAINMENT",
  SUM(
    CASE
      WHEN NOT TARGET_LAG_SEC IS NULL AND ACTUAL_LAG_SEC > TARGET_LAG_SEC
      THEN 1
      ELSE 0
    END
  ) AS "DQ_SLA_BREACH_COUNT"
FROM (
  SELECT
    "QUALIFIED_NAME" AS QUALIFIED_NAME,
    "NAME" AS DYNAMIC_TABLE_NAME,
    "DATABASE_NAME" AS DATABASE_NAME,
    "SCHEMA_NAME" AS SCHEMA_NAME,
    "STATE" AS REFRESH_STATE,
    "STATE_MESSAGE" AS STATE_MESSAGE,
    "REFRESH_ACTION" AS REFRESH_ACTION,
    "REFRESH_TRIGGER" AS REFRESH_TRIGGER,
    "TARGET_LAG_SEC" AS TARGET_LAG_SEC,
    (
      TRY_TO_TIMESTAMP_NTZ("REFRESH_START_TIME")
    ) AS REFRESH_START_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("REFRESH_END_TIME")
    ) AS REFRESH_END_AT,
    (
      TRY_TO_TIMESTAMP_NTZ("DATA_TIMESTAMP")
    ) AS DATA_TIMESTAMP_AT,
    (
      DATEDIFF(
        SECOND,
        (
          TRY_TO_TIMESTAMP_NTZ("DATA_TIMESTAMP")
        ),
        (
          TRY_TO_TIMESTAMP_NTZ("REFRESH_START_TIME")
        )
      )
    ) AS ACTUAL_LAG_SEC,
    (
      DATEDIFF(
        SECOND,
        (
          TRY_TO_TIMESTAMP_NTZ("REFRESH_START_TIME")
        ),
        (
          TRY_TO_TIMESTAMP_NTZ("REFRESH_END_TIME")
        )
      )
    ) AS REFRESH_DURATION_SEC
  FROM dynamic_table_refresh_history
) AS base
GROUP BY
  (
    DATE_TRUNC('DAY', "REFRESH_START_AT")
  ),
  QUALIFIED_NAME,
  DATABASE_NAME,
  SCHEMA_NAME,
  CASE
    WHEN TARGET_LAG_SEC IS NULL
    THEN 'NO_TARGET'
    WHEN ACTUAL_LAG_SEC > TARGET_LAG_SEC
    THEN 'BREACHED'
    ELSE 'WITHIN_TARGET'
  END;
