-- Pipeline Reliability 1.0.0 — semantic view
--
-- Cortex Analyst reads this view to answer questions about the product.
-- 18 verified queries teach it the team's vocabulary.
--
-- Additive measures are METRICS; ratios, percentiles, and distinct counts
-- are FACTS, because re-aggregating them would produce a wrong number.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE SNOWOBS_PUBLISHER;

CREATE OR REPLACE SEMANTIC VIEW OBSERVABILITY.SEMANTIC.PIPELINE_HEALTH
  TABLES (
    pipeline_health_task_run AS OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
      PRIMARY KEY (TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA)
      COMMENT = 'Pipeline Reliability: Task run.',
    pipeline_health_dynamic_table_refresh AS OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
      PRIMARY KEY (TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS)
      COMMENT = 'Pipeline Reliability: Dynamic table refresh.'
  )
  FACTS (
    pipeline_health_task_run.PIPE_TASK_SUCCESS_RATE AS PIPE_TASK_SUCCESS_RATE
      WITH SYNONYMS = ('pipeline success rate', 'task reliability', 'task success', 'task success rate')
      COMMENT = 'Share of task runs that completed successfully. SKIPPED runs are in the denominator on purpose: a graph that is repeatedly suspended is not delivering data, however healthy its individual statements look. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    pipeline_health_task_run.PIPE_TASK_DURATION_P95 AS PIPE_TASK_DURATION_P95
      WITH SYNONYMS = ('p95 task duration', 'p95 task time', 'slow tasks', 'task latency', 'task runtime')
      COMMENT = '95th-percentile wall-clock duration from scheduled time to completion, per task. Measured from *scheduled* rather than started time deliberately: a task that waits ten minutes for a warehouse has been late by ten minutes, whatever its statement timing says. The percentile is taken from a nearest-rank window computed over the task''s retained history rather than through the PERCENTILE shim, because Snowflake estimates percentiles from a t-digest and DuckDB computes them exactly — a difference no task-duration tail has enough observations to absorb. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    pipeline_health_dynamic_table_refresh.PIPE_DT_LAG_VS_TARGET AS PIPE_DT_LAG_VS_TARGET
      WITH SYNONYMS = ('dt lag', 'dynamic table lag', 'dynamic table lag vs target', 'freshness vs target', 'target lag ratio')
      COMMENT = 'Actual lag as a fraction of declared TARGET_LAG. At or below 100% the table is meeting the freshness contract it advertises; above it, downstream consumers are reading data older than they were promised. Expressed as a ratio rather than raw seconds so tables with different targets are comparable on one axis. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.',
    pipeline_health_dynamic_table_refresh.DQ_FRESHNESS_SLA_ATTAINMENT AS DQ_FRESHNESS_SLA_ATTAINMENT
      WITH SYNONYMS = ('freshness compliance', 'freshness sla', 'freshness sla attainment', 'on-time refreshes', 'sla attainment')
      COMMENT = 'Share of dynamic-table refreshes that met the table''s own declared TARGET_LAG. Refreshes on tables with no target are excluded from both sides of the ratio rather than counted as successes — this measures attainment against stated SLAs, not the absence of one. Published as a row-level fact: this figure does not survive being re-aggregated over a coarser grain.'
  )
  DIMENSIONS (
    pipeline_health_task_run.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over SCHEDULED_AT, at the coarsest grain the product''s metrics declare.',
    pipeline_health_task_run.TASK AS TASK
      WITH SYNONYMS = ('task')
      COMMENT = 'Task name.',
    pipeline_health_task_run.GRAPH_ROOT AS GRAPH_ROOT
      WITH SYNONYMS = ('graph root')
      COMMENT = 'Root task of the DAG the run belongs to — the roll-up key.',
    pipeline_health_task_run.ERROR_CLASS AS ERROR_CLASS
      WITH SYNONYMS = ('error class')
      COMMENT = 'Snowflake error code of the run, or NONE when it succeeded.',
    pipeline_health_task_run.DATABASE AS DATABASE
      WITH SYNONYMS = ('database')
      COMMENT = 'Database the task is defined in.',
    pipeline_health_task_run.TASK_SCHEMA AS TASK_SCHEMA
      WITH SYNONYMS = ('task schema')
      COMMENT = 'Schema the task is defined in.',
    pipeline_health_dynamic_table_refresh.TIME_BUCKET AS TIME_BUCKET
      WITH SYNONYMS = ('date', 'day', 'period', 'time bucket', 'time period')
      COMMENT = 'Time bucket over REFRESH_START_AT, at the coarsest grain the product''s metrics declare.',
    pipeline_health_dynamic_table_refresh.DYNAMIC_TABLE AS DYNAMIC_TABLE
      WITH SYNONYMS = ('dynamic table')
      COMMENT = 'Fully qualified dynamic table name.',
    pipeline_health_dynamic_table_refresh.DATABASE AS DATABASE
      WITH SYNONYMS = ('database')
      COMMENT = 'Database the dynamic table lives in.',
    pipeline_health_dynamic_table_refresh.TABLE_SCHEMA AS TABLE_SCHEMA
      WITH SYNONYMS = ('table schema')
      COMMENT = 'Schema the dynamic table lives in.',
    pipeline_health_dynamic_table_refresh.SLA_STATUS AS SLA_STATUS
      WITH SYNONYMS = ('sla status')
      COMMENT = 'Whether the refresh met its declared TARGET_LAG.'
  )
  METRICS (
    pipeline_health_task_run.PIPE_TASK_FAILURES AS SUM(PIPE_TASK_FAILURES)
      WITH SYNONYMS = ('failed tasks', 'pipeline failures', 'task errors', 'task failures')
      COMMENT = 'Count of task runs that ended in FAILED. Sliced by error class this separates the timeouts from the genuinely broken SQL, which want different responses.',
    pipeline_health_task_run.PIPE_ROOT_FAILURES AS SUM(PIPE_ROOT_FAILURES)
      WITH SYNONYMS = ('dag root failures', 'root cause failures', 'root task failures', 'upstream failures')
      COMMENT = 'Failures at the root of a task graph — the incidents worth paging on. A root failure suspends everything beneath it, so this count is what an alert should carry while the downstream SKIPPED runs stay context rather than separate notifications.',
    pipeline_health_task_run.PIPE_SKIPPED_DOWNSTREAM AS SUM(PIPE_SKIPPED_DOWNSTREAM)
      WITH SYNONYMS = ('downstream impact', 'skipped downstream runs', 'skipped tasks', 'suspended graph')
      COMMENT = 'Runs skipped because something upstream failed. Read against pipe.root_failures this is the blast radius of an incident: one root failure, twelve tables that did not refresh.',
    pipeline_health_dynamic_table_refresh.PIPE_DT_LAG_BREACHES AS SUM(PIPE_DT_LAG_BREACHES)
      WITH SYNONYMS = ('dynamic table lag breaches', 'lag breaches', 'stale dynamic tables', 'target lag misses')
      COMMENT = 'Refreshes that started against data older than the table''s TARGET_LAG. Refreshes with no declared target are excluded rather than counted as passing — an unstated SLA is not a met one.',
    pipeline_health_dynamic_table_refresh.PIPE_DT_REFRESH_FAILURES AS SUM(PIPE_DT_REFRESH_FAILURES)
      WITH SYNONYMS = ('dt failures', 'dynamic table errors', 'dynamic table refresh failures', 'failed refreshes')
      COMMENT = 'Refreshes that did not succeed, including UPSTREAM_FAILED — a dynamic table whose source failed is just as stale as one that failed itself, and the consumer cannot tell the difference.',
    pipeline_health_dynamic_table_refresh.DQ_SLA_BREACH_COUNT AS SUM(DQ_SLA_BREACH_COUNT)
      WITH SYNONYMS = ('breach count', 'freshness sla breaches', 'missed freshness', 'sla breaches')
      COMMENT = 'Number of refreshes that missed their declared target lag. Counted per refresh rather than per table so a table that breaches every hour is visibly worse than one that breached once.'
  )
  COMMENT = 'Task and dynamic-table reliability: success rate, failures attributed to the root of the dependency graph rather than every leaf it broke, duration drift, refresh lag against TARGET_LAG, and freshness SLA attainment. This is the product an on-call engineer reads at 03:00, so it carries the coarsest honest freshness of its sources and says so.'
  AI_VERIFIED_QUERIES (
    vq_pipe_task_success_rate_1 AS (
      QUESTION 'task success rate this week'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_SUCCESS_RATE
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_TASK_SUCCESS_RATE DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_task_success_rate_2 AS (
      QUESTION 'least reliable tasks'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_SUCCESS_RATE
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_TASK_SUCCESS_RATE DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_task_failures_1 AS (
      QUESTION 'task failures yesterday'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_TASK_FAILURES) AS PIPE_TASK_FAILURES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_TASK_FAILURES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_task_failures_2 AS (
      QUESTION 'failures by error code'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_TASK_FAILURES) AS PIPE_TASK_FAILURES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_TASK_FAILURES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_root_failures_1 AS (
      QUESTION 'root task failures'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_ROOT_FAILURES) AS PIPE_ROOT_FAILURES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_ROOT_FAILURES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_root_failures_2 AS (
      QUESTION 'which DAG root failed last night'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_ROOT_FAILURES) AS PIPE_ROOT_FAILURES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_ROOT_FAILURES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_skipped_downstream_1 AS (
      QUESTION 'how many tasks were skipped'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_SKIPPED_DOWNSTREAM) AS PIPE_SKIPPED_DOWNSTREAM
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_SKIPPED_DOWNSTREAM DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_skipped_downstream_2 AS (
      QUESTION 'blast radius of last night''s failure'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_SKIPPED_DOWNSTREAM) AS PIPE_SKIPPED_DOWNSTREAM
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA
ORDER BY PIPE_SKIPPED_DOWNSTREAM DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_task_duration_p95_1 AS (
      QUESTION 'slowest tasks'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_DURATION_P95
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_TASK_DURATION_P95 DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_task_duration_p95_2 AS (
      QUESTION 'p95 task duration by schema'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_DURATION_P95
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_TASK_DURATION_P95 DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_dt_lag_vs_target_1 AS (
      QUESTION 'dynamic tables missing their target lag'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, PIPE_DT_LAG_VS_TARGET
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_DT_LAG_VS_TARGET DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_dt_lag_vs_target_2 AS (
      QUESTION 'dt lag ratio this week'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, PIPE_DT_LAG_VS_TARGET
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY PIPE_DT_LAG_VS_TARGET DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_dt_lag_breaches_1 AS (
      QUESTION 'lag breaches by dynamic table'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, SUM(PIPE_DT_LAG_BREACHES) AS PIPE_DT_LAG_BREACHES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS
ORDER BY PIPE_DT_LAG_BREACHES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_dt_lag_breaches_2 AS (
      QUESTION 'which dynamic tables breached yesterday'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, SUM(PIPE_DT_LAG_BREACHES) AS PIPE_DT_LAG_BREACHES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS
ORDER BY PIPE_DT_LAG_BREACHES DESC NULLS LAST
LIMIT 20'
    ),
    vq_pipe_dt_refresh_failures_1 AS (
      QUESTION 'dynamic table refresh failures by dynamic table over the last 30 days'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, SUM(PIPE_DT_REFRESH_FAILURES) AS PIPE_DT_REFRESH_FAILURES
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS
ORDER BY PIPE_DT_REFRESH_FAILURES DESC NULLS LAST
LIMIT 20'
    ),
    vq_dq_freshness_sla_attainment_1 AS (
      QUESTION 'freshness SLA attainment this month'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, DQ_FRESHNESS_SLA_ATTAINMENT
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY DQ_FRESHNESS_SLA_ATTAINMENT DESC NULLS LAST
LIMIT 20'
    ),
    vq_dq_freshness_sla_attainment_2 AS (
      QUESTION 'which tables miss their SLA'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, DQ_FRESHNESS_SLA_ATTAINMENT
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY DQ_FRESHNESS_SLA_ATTAINMENT DESC NULLS LAST
LIMIT 20'
    ),
    vq_dq_sla_breach_count_1 AS (
      QUESTION 'freshness SLA breaches by dynamic table over the last 30 days'
      VERIFIED_AT 1787529600
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(support = data-engineering@internal)'
      SQL 'SELECT DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, SUM(DQ_SLA_BREACH_COUNT) AS DQ_SLA_BREACH_COUNT
FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS
ORDER BY DQ_SLA_BREACH_COUNT DESC NULLS LAST
LIMIT 20'
    )
  )
;
