-- Pipeline Reliability 1.0.0 — share and organization listing
--
-- Publishes the product to the organization's internal marketplace.
--
-- The share carries the PUBLISHED and SEMANTIC schemas only — never the
-- curated or raw layers — and grants each object by name.
--
-- PUBLISH = FALSE: the listing is created but not offered. Publishing it
-- to the organization is a separate, deliberate act by a human (R8).
--
-- Requires ORGADMIN (or an organization account) to create an
-- organization listing.
--
-- Generated by the Observability & FinOps Platform. Review before running.
-- The platform does not execute this script; a human does (R2, R8).

USE ROLE ACCOUNTADMIN;

CREATE SHARE IF NOT EXISTS SHARE_PIPELINE_HEALTH
  COMMENT = 'Pipeline Reliability 1.0.0 — internal share';

GRANT USAGE ON DATABASE OBSERVABILITY TO SHARE SHARE_PIPELINE_HEALTH;
GRANT USAGE ON SCHEMA OBSERVABILITY.PUBLISHED TO SHARE SHARE_PIPELINE_HEALTH;
GRANT USAGE ON SCHEMA OBSERVABILITY.SEMANTIC TO SHARE SHARE_PIPELINE_HEALTH;

GRANT SELECT ON VIEW OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN TO SHARE SHARE_PIPELINE_HEALTH;
GRANT SELECT ON VIEW OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH TO SHARE SHARE_PIPELINE_HEALTH;

GRANT REFERENCES ON SEMANTIC VIEW OBSERVABILITY.SEMANTIC.PIPELINE_HEALTH TO SHARE SHARE_PIPELINE_HEALTH;

CREATE ORGANIZATION LISTING IF NOT EXISTS LST_PIPELINE_HEALTH
  SHARE SHARE_PIPELINE_HEALTH
  AS $$
title: Pipeline Reliability
subtitle: 'Task and dynamic-table reliability: success rate, failures attributed to the root of the dependency
  graph rath'
description: "Task and dynamic-table reliability: success rate, failures attributed to the root of the\
  \ dependency graph rather than every leaf it broke, duration drift, refresh lag against TARGET_LAG,\
  \ and freshness SLA attainment. This is the product an on-call engineer reads at 03:00, so it carries\
  \ the coarsest honest freshness of its sources and says so.\n\nOwner: data-engineering · support: data-engineering@internal\n\
  Classification: internal\nFreshness guarantee: 3 h (the documented latency of the slowest source behind\
  \ this product).\nAvailability target: 99.5% · retention: 365 days\nDeprecation notice: 60 days\n\n\
  Relations (2):\n  - V_PIPELINE_HEALTH_TASK_RUN — 11 columns, grain TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS,\
  \ DATABASE, TASK_SCHEMA, freshness 45 min\n  - V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH — 10 columns,\
  \ grain TIME_BUCKET, DYNAMIC_TABLE, DATABASE, TABLE_SCHEMA, SLA_STATUS, freshness 3 h\n\nGoverned metrics\
  \ (10): dq.freshness_sla_attainment, dq.sla_breach_count, pipe.dt_lag_breaches, pipe.dt_lag_vs_target,\
  \ pipe.dt_refresh_failures, pipe.root_failures, pipe.skipped_downstream, pipe.task_duration_p95, pipe.task_failures,\
  \ pipe.task_success_rate\n\nBreaking-change policy: Removing a column, changing its type, relaxing its\
  \ nullability, rebinding it to a different governed metric, changing the grain, loosening the freshness\
  \ guarantee, or shortening retention is a BREAKING change: it requires a major version, a migration\
  \ note, and the full deprecation notice period. Everything else is additive and ships as a minor or\
  \ patch version."
organization_profile: INTERNAL
organization_targets:
  access:
  - all_accounts: true
  support_contact: data-engineering@internal
  approver_contact: data-engineering@internal
auto_fulfillment:
  refresh_schedule: 1 HOUR
  refresh_type: SUB_DATABASE
categories:
- IT_OPERATIONS
- DATA_QUALITY
resources:
  documentation: https://internal.docs/data-products/pipeline-health
  support: data-engineering@internal
data_dictionary:
  featured:
  - database_name: OBSERVABILITY
    objects:
    - name: V_PIPELINE_HEALTH_TASK_RUN
      schema: PUBLISHED
      domain: VIEW
    - name: V_PIPELINE_HEALTH_DYNAMIC_TABLE_REFRESH
      schema: PUBLISHED
      domain: VIEW
    - name: PIPELINE_HEALTH
      schema: SEMANTIC
      domain: SEMANTIC_VIEW
usage_examples:
- title: task success rate this week
  description: Answered from the product's own published views; the same SQL is a verified query on the
    PIPELINE_HEALTH semantic view.
  query: 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_SUCCESS_RATE

    FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    ORDER BY PIPE_TASK_SUCCESS_RATE DESC NULLS LAST

    LIMIT 20;'
- title: least reliable tasks
  description: Answered from the product's own published views; the same SQL is a verified query on the
    PIPELINE_HEALTH semantic view.
  query: 'SELECT TIME_BUCKET, TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, PIPE_TASK_SUCCESS_RATE

    FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    ORDER BY PIPE_TASK_SUCCESS_RATE DESC NULLS LAST

    LIMIT 20;'
- title: task failures yesterday
  description: Answered from the product's own published views; the same SQL is a verified query on the
    PIPELINE_HEALTH semantic view.
  query: 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_TASK_FAILURES) AS PIPE_TASK_FAILURES

    FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA

    ORDER BY PIPE_TASK_FAILURES DESC NULLS LAST

    LIMIT 20;'
- title: failures by error code
  description: Answered from the product's own published views; the same SQL is a verified query on the
    PIPELINE_HEALTH semantic view.
  query: 'SELECT TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA, SUM(PIPE_TASK_FAILURES) AS PIPE_TASK_FAILURES

    FROM OBSERVABILITY.PUBLISHED.V_PIPELINE_HEALTH_TASK_RUN

    WHERE TIME_BUCKET >= DATEADD(day, -30, CURRENT_DATE())

    GROUP BY TASK, GRAPH_ROOT, ERROR_CLASS, DATABASE, TASK_SCHEMA

    ORDER BY PIPE_TASK_FAILURES DESC NULLS LAST

    LIMIT 20;'
$$
  PUBLISH = FALSE;

SHOW ORGANIZATION LISTINGS LIKE 'LST_PIPELINE_HEALTH';
